// ─── BANNERS TURÍSTICOS DE CHILE ──────────────────────────────────────────────
// Imágenes vía Unsplash (gratuitas, sin API key)
// Rotan en todos los banners del sitio

export const CHILE_BANNERS = [
  {
    id: 1,
    city: 'Pucón',
    region: 'La Araucanía',
    tagline: 'Despierta con el Villarrica',
    description: 'Aventura, termas y naturaleza pura al pie del volcán más activo de Chile.',
    image: 'https://images.unsplash.com/photo-1601059381817-9ad55a5a6dc3?w=1200&q=80',
    color: '#1a3c2c',
    accent: '#52b788',
    emoji: '🌋',
    tags: ['Aventura', 'Naturaleza', 'Termas'],
  },
  {
    id: 2,
    city: 'Valparaíso',
    region: 'Valparaíso',
    tagline: 'Vive el puerto eterno',
    description: 'Cerros llenos de arte, historia y los atardeceres más hermosos del Pacífico.',
    image: 'https://images.unsplash.com/photo-1548789573-c56db4b86718?w=1200&q=80',
    color: '#1e3a5f',
    accent: '#60a5fa',
    emoji: '🎨',
    tags: ['Arte', 'Historia', 'Mar'],
  },
  {
    id: 3,
    city: 'San Pedro de Atacama',
    region: 'Antofagasta',
    tagline: 'El desierto te llama',
    description: 'Géiseres al amanecer, lagunas de colores y el cielo estrellado más puro del mundo.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    color: '#7c2d12',
    accent: '#fb923c',
    emoji: '🌵',
    tags: ['Desierto', 'Astroturismo', 'Cultura'],
  },
  {
    id: 4,
    city: 'Frutillar',
    region: 'Los Lagos',
    tagline: 'Disfruta Frutillar',
    description: 'Casas bavaras, el lago Llanquihue y el volcán Osorno reflejado en el agua.',
    image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=1200&q=80',
    color: '#1c3d5a',
    accent: '#38bdf8',
    emoji: '🏔️',
    tags: ['Lago', 'Cultura', 'Tranquilidad'],
  },
  {
    id: 5,
    city: 'Torres del Paine',
    region: 'Magallanes',
    tagline: 'El fin del mundo te espera',
    description: 'Torres de granito, glaciares azules y fauna patagónica en estado puro.',
    image: 'https://images.unsplash.com/photo-1531761535209-180857e963b9?w=1200&q=80',
    color: '#0f2942',
    accent: '#7dd3fc',
    emoji: '🏕️',
    tags: ['Trekking', 'Patagonia', 'Naturaleza'],
  },
  {
    id: 6,
    city: 'Viña del Mar',
    region: 'Valparaíso',
    tagline: 'Vacaciones en la Ciudad Jardín',
    description: 'Playas, casino, flores y el mejor clima de la costa central de Chile.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
    color: '#164e63',
    accent: '#22d3ee',
    emoji: '🌊',
    tags: ['Playa', 'Ciudad', 'Gastronomía'],
  },
  {
    id: 7,
    city: 'Papudo',
    region: 'Valparaíso',
    tagline: 'Vacaciones en Papudo',
    description: 'El balneario más pintoresco de Chile. Caleta de pescadores, playas tranquilas y aire puro.',
    image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=80',
    color: '#0c4a6e',
    accent: '#38bdf8',
    emoji: '⚓',
    tags: ['Playa', 'Tranquilidad', 'Familia'],
  },
  {
    id: 8,
    city: 'Puerto Varas',
    region: 'Los Lagos',
    tagline: 'La ciudad de las rosas',
    description: 'Arquitectura alemana, el lago Llanquihue y el imponente volcán Osorno como telón de fondo.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
    color: '#1e3a5f',
    accent: '#93c5fd',
    emoji: '🌹',
    tags: ['Lago', 'Gastronomía', 'Aventura'],
  },
  {
    id: 9,
    city: 'La Serena',
    region: 'Coquimbo',
    tagline: 'Sol y estrellas en La Serena',
    description: 'Playas de arena blanca, valle del Elqui y los mejores observatorios astronómicos del mundo.',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&q=80',
    color: '#713f12',
    accent: '#fbbf24',
    emoji: '⭐',
    tags: ['Playa', 'Astroturismo', 'Valle'],
  },
  {
    id: 10,
    city: 'Chiloé',
    region: 'Los Lagos',
    tagline: 'La magia de Chiloé',
    description: 'Iglesias patrimonio UNESCO, palafitos de colores y la mejor comida de mar de Chile.',
    image: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=1200&q=80',
    color: '#1c3d5a',
    accent: '#f97316',
    emoji: '⛵',
    tags: ['Cultura', 'Gastronomía', 'Patrimonio'],
  },
  {
    id: 11,
    city: 'Olmué',
    region: 'Valparaíso',
    tagline: 'Respira Olmué',
    description: 'El corazón verde de la región. Quebrada de la Plata, camping y naturaleza a pasos de Santiago.',
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&q=80',
    color: '#14532d',
    accent: '#86efac',
    emoji: '🌿',
    tags: ['Naturaleza', 'Senderismo', 'Familia'],
  },
  {
    id: 12,
    city: 'Pichilemu',
    region: "O'Higgins",
    tagline: 'Las olas te esperan',
    description: 'Capital del surf en Chile. Punta de Lobos, atardeceres de película y brisa de mar todo el año.',
    image: 'https://images.unsplash.com/photo-1455729552865-3658a5d39692?w=1200&q=80',
    color: '#0f3460',
    accent: '#4ade80',
    emoji: '🏄',
    tags: ['Surf', 'Playa', 'Aventura'],
  },
  {
    id: 13,
    city: 'Zapallar',
    region: 'Valparaíso',
    tagline: 'Elegancia frente al mar',
    description: 'El balneario más exclusivo de Chile. Caleta íntima, vegetación exuberante y mar cristalino.',
    image: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1200&q=80',
    color: '#134e4a',
    accent: '#2dd4bf',
    emoji: '🌺',
    tags: ['Playa', 'Relax', 'Gastronomía'],
  },
  {
    id: 14,
    city: 'Villarrica',
    region: 'La Araucanía',
    tagline: 'Lago y volcán en Villarrica',
    description: 'El lago más famoso de la Araucanía, rodeado de bosques nativos y con el volcán siempre presente.',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80',
    color: '#1a3c2c',
    accent: '#4ade80',
    emoji: '🏕️',
    tags: ['Lago', 'Naturaleza', 'Aventura'],
  },
  {
    id: 15,
    city: 'Arica',
    region: 'Arica y Parinacota',
    tagline: 'La ciudad de la eterna primavera',
    description: 'El norte extremo de Chile: playas desérticas, el Morro y cultura aymara a flor de piel.',
    image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80',
    color: '#7c2d12',
    accent: '#fb923c',
    emoji: '☀️',
    tags: ['Playa', 'Cultura', 'Historia'],
  },
  {
    id: 16,
    city: 'Valdivia',
    region: 'Los Ríos',
    tagline: 'El río te invita a Valdivia',
    description: 'Cervecerías artesanales, mercado fluvial, lobos de mar y una naturaleza que enamora.',
    image: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=1200&q=80',
    color: '#1c3d5a',
    accent: '#fbbf24',
    emoji: '🦭',
    tags: ['Gastronomía', 'Río', 'Cultura'],
  },
  {
    id: 17,
    city: 'Constitución',
    region: 'Maule',
    tagline: 'El salvaje litoral del Maule',
    description: 'Formaciones rocosas únicas, playas vírgenes y el río Maule encontrándose con el Pacífico.',
    image: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=1200&q=80',
    color: '#0f2942',
    accent: '#60a5fa',
    emoji: '🌊',
    tags: ['Playa', 'Naturaleza', 'Surf'],
  },
  {
    id: 18,
    city: 'Santa Cruz',
    region: "O'Higgins",
    tagline: 'Vive la ruta del vino',
    description: 'El corazón de la viña chilena. Bodegas de clase mundial, gastronomía y el valle de Colchagua.',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=1200&q=80',
    color: '#4a1942',
    accent: '#c084fc',
    emoji: '🍷',
    tags: ['Vino', 'Gastronomía', 'Cultura'],
  },
  {
    id: 19,
    city: 'Tongoy',
    region: 'Coquimbo',
    tagline: 'Verano eterno en Tongoy',
    description: 'La bahía más grande de Chile, aguas tranquilas y el mejor marisquito del norte chico.',
    image: 'https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?w=1200&q=80',
    color: '#0c4a6e',
    accent: '#38bdf8',
    emoji: '🦞',
    tags: ['Playa', 'Gastronomía', 'Familia'],
  },
  {
    id: 20,
    city: 'Antuco',
    region: 'Biobío',
    tagline: 'Descubre la sierra del Biobío',
    description: 'Volcán Antuco, laguna de la Laja y nieve en invierno. El secreto mejor guardado del sur.',
    image: 'https://images.unsplash.com/photo-1476611338391-6f395a0ebc7b?w=1200&q=80',
    color: '#1a3c2c',
    accent: '#a3e635',
    emoji: '⛷️',
    tags: ['Nieve', 'Aventura', 'Naturaleza'],
  },
]

// ── HELPERS ───────────────────────────────────────────────────────────────────

// Obtener banner aleatorio
export function getRandomBanner() {
  return CHILE_BANNERS[Math.floor(Math.random() * CHILE_BANNERS.length)]
}

// Obtener N banners aleatorios sin repetir
export function getRandomBanners(n = 5) {
  const shuffled = [...CHILE_BANNERS].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, Math.min(n, CHILE_BANNERS.length))
}

// Obtener banner por ciudad
export function getBannerByCity(city) {
  return CHILE_BANNERS.find(b => b.city.toLowerCase() === city.toLowerCase())
}
