export function toSlug(str) {
  return str
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

export const COUNTRY_SLUGS = {
  chile:     { name: 'Chile',     code: 'CL', flag: '🇨🇱' },
  argentina: { name: 'Argentina', code: 'AR', flag: '🇦🇷' },
  colombia:  { name: 'Colombia',  code: 'CO', flag: '🇨🇴' },
  mexico:    { name: 'México',    code: 'MX', flag: '🇲🇽' },
}

export const countryData = {
  chile: {
    name: 'Chile',
    code: 'CL',
    flag: '🇨🇱',
    description: 'Chile es uno de los destinos más diversos del planeta: en pocas horas puedes pasar del desierto más árido del mundo a fiordos patagónicos, viñedos de altura o playas del Pacífico. Su larga franja costera y la variedad de microclimas lo convierten en un destino ideal para el intercambio de hogares durante todo el año.',
    topCities: ['Santiago', 'Valparaíso', 'Viña del Mar', 'Pucón', 'Puerto Varas'],
    bestSeason: 'Diciembre a marzo (verano austral) para playas y aventura al aire libre; junio a agosto para esquí en Los Andes.',
    language: 'Español',
    currency: 'Peso chileno (CLP)',
    approxHomes: 45,
    keywords: ['intercambio de hogares en Chile', 'home exchange Chile', 'intercambiar casa Chile', 'alojamiento gratis Chile', 'hospedaje intercambio Chile'],
  },
  argentina: {
    name: 'Argentina',
    code: 'AR',
    flag: '🇦🇷',
    description: 'Argentina combina la efervescencia cultural de Buenos Aires con la majestuosidad de la Patagonia, los viñedos de Mendoza y las quebradas norteñas. Es un país de contrastes geográficos y culturales que ofrece experiencias únicas para quienes viajan a través del intercambio de hogares.',
    topCities: ['Buenos Aires', 'Mendoza', 'Bariloche', 'Córdoba', 'Salta'],
    bestSeason: 'Octubre a marzo para el norte y Buenos Aires; junio a septiembre para esquí en Bariloche.',
    language: 'Español',
    currency: 'Peso argentino (ARS)',
    approxHomes: 38,
    keywords: ['intercambio de hogares en Argentina', 'home exchange Argentina', 'intercambiar casa Argentina', 'alojamiento gratis Argentina', 'hospedaje intercambio Argentina'],
  },
  colombia: {
    name: 'Colombia',
    code: 'CO',
    flag: '🇨🇴',
    description: 'Colombia es un país de primavera eterna, con una biodiversidad asombrosa y ciudades que combinan tradición colonial con modernidad vibrante. De Bogotá a Cartagena, pasando por los cafetales del Eje Cafetero y las playas del Caribe, Colombia ofrece un mosaico de experiencias para el viajero que intercambia hogar.',
    topCities: ['Bogotá', 'Medellín', 'Cartagena', 'Cali', 'Santa Marta'],
    bestSeason: 'Diciembre a marzo y julio a agosto (temporadas secas en gran parte del país).',
    language: 'Español',
    currency: 'Peso colombiano (COP)',
    approxHomes: 29,
    keywords: ['intercambio de hogares en Colombia', 'home exchange Colombia', 'intercambiar casa Colombia', 'alojamiento gratis Colombia', 'hospedaje intercambio Colombia'],
  },
  mexico: {
    name: 'México',
    code: 'MX',
    flag: '🇲🇽',
    description: 'México es un país de civilizaciones milenarias, gastronomía Patrimonio de la Humanidad y una diversidad geográfica que va del Caribe turquesa al desierto de Baja California. Sus ciudades coloniales, playas del Pacífico y selvas mayas lo convierten en uno de los destinos preferidos para el intercambio de hogares en América Latina.',
    topCities: ['Ciudad de México', 'Guadalajara', 'Oaxaca', 'San Miguel de Allende', 'Mérida'],
    bestSeason: 'Noviembre a abril (temporada seca) para la mayoría de destinos; evitar el Caribe en septiembre-octubre por huracanes.',
    language: 'Español',
    currency: 'Peso mexicano (MXN)',
    approxHomes: 52,
    keywords: ['intercambio de hogares en México', 'home exchange México', 'intercambiar casa México', 'alojamiento gratis México', 'hospedaje intercambio México'],
  },
}

export const cityData = {
  // ── CHILE ──────────────────────────────────────────────────────────────
  santiago: {
    name: 'Santiago',
    country: 'chile',
    description: 'Santiago es la capital y motor cultural de Chile, enclavada entre la Cordillera de los Andes y la Cordillera de la Costa. Combina barrios bohemios como Bellavista y Italia con centros financieros y una escena gastronómica que ha puesto a la ciudad en el mapa latinoamericano. Desde allí, los Andes y el mar están a menos de dos horas.',
    highlights: [
      'Barrio Italia y Barrio Yungay: gastronomía, diseño y cultura local',
      'Cerro San Cristóbal: mirador panorámico con vista a la cordillera',
      'Mercado Central: el templo del marisco fresco en el corazón de la ciudad',
      'Viña Concha y Toro y Valle del Maipo: enoturismo a 40 minutos',
      'Centro Cívico: La Moneda, Plaza de Armas y museos gratuitos',
      'Ski centers a 1 hora: Valle Nevado, La Parva y El Colorado',
    ],
    bestSeason: 'Septiembre a noviembre y marzo a mayo — primavera y otoño traen temperaturas perfectas y cielos despejados.',
    avgPricePerNight: 50,
    heroImage: 'https://images.unsplash.com/photo-1568659706081-e0f6a5ebbae4?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1568659706081-e0f6a5ebbae4?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 60',
      dinnerForTwo: '~USD 22',
      avgTemp: '17°C',
      airportDistance: '14 km · SCL',
      currency: 'Peso Chileno / CLP',
    },
    keywords: ['intercambio de hogares en Santiago', 'home exchange Santiago', 'intercambiar casa en Santiago', 'alojamiento gratis Santiago', 'hospedaje intercambio Santiago Chile'],
  },
  valparaiso: {
    name: 'Valparaíso',
    country: 'chile',
    description: 'Valparaíso es una ciudad-poema pintada sobre 42 cerros que caen al Océano Pacífico. Patrimonio de la Humanidad por la UNESCO, sus calles empinadas y ascensores centenarios esconden murales de artistas de todo el mundo. La ciudad vive entre su tradición portuaria y una cultura alternativa que la hace única en Chile.',
    highlights: [
      'Cerros Alegre y Concepción: murales, cafés y arquitectura colorida',
      'Ascensor Peral y otros funiculares históricos',
      'Puerto de Valparaíso: vista del Pacífico desde el Paseo 21 de Mayo',
      'Mercado El Cardonal: la vida portuaria en su expresión más auténtica',
      'Ruta del vino Casablanca: a 30 minutos entre viñedos de altura',
      'Año Nuevo: los fuegos artificiales sobre la bahía son de los más famosos del mundo',
    ],
    bestSeason: 'Diciembre a marzo — verano chileno con días soleados y brisas del Pacífico.',
    avgPricePerNight: 40,
    heroImage: 'https://images.unsplash.com/photo-1601171975848-b9de38a6e32c?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1601171975848-b9de38a6e32c?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 45',
      dinnerForTwo: '~USD 15',
      avgTemp: '16°C',
      airportDistance: '110 km · SCL',
      currency: 'Peso Chileno / CLP',
    },
    keywords: ['intercambio de hogares en Valparaíso', 'home exchange Valparaíso', 'intercambiar casa en Valparaíso', 'alojamiento gratis Valparaíso', 'hospedaje intercambio Valparaíso'],
  },
  'vina-del-mar': {
    name: 'Viña del Mar',
    country: 'chile',
    description: 'Viña del Mar, la Ciudad Jardín, es el balneario por excelencia de Chile. Sus playas de arena blanca, el Casino Municipal y sus avenidas arboladas atraen a miles de visitantes durante el verano austral. La cercanía con Valparaíso permite combinar la relajación costera con la bohemia porteña en el mismo día.',
    highlights: [
      'Playa de Viña y Playa Reñaca: las más concurridas del litoral central',
      'Jardín Botánico Nacional: 400 hectáreas de flora chilena y exótica',
      'Festival Internacional de la Canción de Viña del Mar (febrero)',
      'Casino de Viña del Mar: símbolo histórico de la ciudad',
      'Cerro Castillo: residencia oficial del Presidente con vistas al mar',
      'Gastón Acurio y gastronomía marina de primer nivel',
    ],
    bestSeason: 'Diciembre a febrero — plena temporada de playa con ambiente festivo.',
    avgPricePerNight: 45,
    heroImage: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f834b?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f834b?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 50',
      dinnerForTwo: '~USD 20',
      avgTemp: '17°C',
      airportDistance: '110 km · SCL',
      currency: 'Peso Chileno / CLP',
    },
    keywords: ['intercambio de hogares en Viña del Mar', 'home exchange Viña del Mar', 'intercambiar casa en Viña del Mar', 'alojamiento gratis Viña del Mar'],
  },
  pucon: {
    name: 'Pucón',
    country: 'chile',
    description: 'Pucón es la capital de la aventura en Chile, ubicada a orillas del Lago Villarrica y bajo la mirada imponente del Volcán Villarrica activo. Es el punto de partida para el rafting en el río Trancura, el ascenso al volcán y la inmersión en aguas termales naturales rodeadas de bosque nativo.',
    highlights: [
      'Ascenso al Volcán Villarrica (2.847 m) con vista al cráter activo',
      'Rafting en el río Trancura: rápidos de clase III y IV',
      'Termas naturales: Los Pozones, Termas Geometricas, Huife',
      'Lago Villarrica: kayak, windsurf y playas de agua dulce',
      'Parque Nacional Huerquehue: lagunas y bosque de araucarias milenarias',
      'Canopy, mountain bike y rappel en cascadas',
    ],
    bestSeason: 'Diciembre a febrero para deportes acuáticos; junio a agosto para esquí en el volcán.',
    avgPricePerNight: 55,
    heroImage: 'https://images.unsplash.com/photo-1521097652996-96d30ae58b6b?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1521097652996-96d30ae58b6b?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 55',
      dinnerForTwo: '~USD 20',
      avgTemp: '14°C',
      airportDistance: '80 km · ZCO',
      currency: 'Peso Chileno / CLP',
    },
    keywords: ['intercambio de hogares en Pucón', 'home exchange Pucón', 'intercambiar casa en Pucón', 'alojamiento gratis Pucón Chile'],
  },
  'puerto-varas': {
    name: 'Puerto Varas',
    country: 'chile',
    description: 'Puerto Varas, la Ciudad de las Rosas, combina la herencia alemana de sus colonos con la grandiosidad de los volcanes Osorno y Calbuco reflejados en el Lago Llanquihue. Es la puerta de entrada a la Patagonia chilena y al Parque Nacional Vicente Pérez Rosales, el más antiguo del país.',
    highlights: [
      'Volcán Osorno y Lago Llanquihue: el paisaje más fotografiado del sur',
      'Parque Nacional Vicente Pérez Rosales: cascadas, lagos y trekking',
      'Saltos del Petrohué: cataratas de agua turquesa en roca volcánica',
      'Gastronomía alemana: küchen, strudel y cerveza artesanal local',
      'Cruce de Lagos: travesía lacustre hacia Bariloche, Argentina',
      'Chiloé: la isla de los palafitos y la mitología chilota a 2 horas',
    ],
    bestSeason: 'Noviembre a marzo — días largos y clima templado en el lago.',
    avgPricePerNight: 60,
    heroImage: 'https://images.unsplash.com/photo-1475070929565-c76b831f379b?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1475070929565-c76b831f379b?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 60',
      dinnerForTwo: '~USD 22',
      avgTemp: '12°C',
      airportDistance: '20 km · PMC',
      currency: 'Peso Chileno / CLP',
    },
    keywords: ['intercambio de hogares en Puerto Varas', 'home exchange Puerto Varas', 'intercambiar casa en Puerto Varas', 'alojamiento gratis Puerto Varas'],
  },
  atacama: {
    name: 'Atacama',
    country: 'chile',
    description: 'El Desierto de Atacama, el más árido del mundo, alberga uno de los cielos más limpios del planeta y paisajes de otro mundo: géiseres a 4.300 metros, lagunas rosadas con flamencos, valles de sal y el oasis de San Pedro de Atacama. Es un destino de astroturismo y aventura de primer nivel mundial.',
    highlights: [
      'Valle de la Luna: formaciones de sal y arenisca al atardecer',
      'Géiseres del Tatio: amanecer entre columnas de vapor a 4.320 m',
      'Laguna Cejar y Laguna Tebenquiche: sal de alta flotabilidad',
      'Laguna Miscanti y Miñiques: flamencos en altiplano andino',
      'Observatorios astronómicos: cielo sin polución lumínica',
      'Salar de Atacama y Laguna Chaxa: flamencos rosados y paisaje selenita',
    ],
    bestSeason: 'Todo el año. Marzo a mayo y septiembre a noviembre ofrecen temperaturas ideales de día y noches frescas.',
    avgPricePerNight: 70,
    heroImage: 'https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 80',
      dinnerForTwo: '~USD 25',
      avgTemp: '20°C',
      airportDistance: '48 km · CJC',
      currency: 'Peso Chileno / CLP',
    },
    keywords: ['intercambio de hogares en Atacama', 'home exchange San Pedro de Atacama', 'intercambiar casa en Atacama', 'alojamiento gratis Atacama Chile'],
  },
  'patagonia-chilena': {
    name: 'Patagonia Chilena',
    country: 'chile',
    description: 'La Patagonia Chilena es uno de los últimos lugares salvajes del planeta: torres de granito que desafían la gravedad, campos de hielo milenarios, fiordos que se adentran cientos de kilómetros y una flora y fauna que no existe en ningún otro lugar. Punta Arenas, Puerto Natales y el Parque Torres del Paine son sus íconos.',
    highlights: [
      'Parque Nacional Torres del Paine: el trekking W y el Circuito son legendarios',
      'Glaciar Grey y Campo de Hielo Sur: navegación entre icebergs',
      'Cueva del Milodón: fósiles de animales prehistóricos',
      'Punta Arenas: ciudad en el Estrecho de Magallanes con pingüineras',
      'Carretera Austral: ruta escénica de 1.240 km por fiordos y glaciares',
      'Puerto Natales: base de expediciones y gastronomía patagónica',
    ],
    bestSeason: 'Noviembre a marzo — vientos más moderados y días de hasta 18 horas de luz.',
    avgPricePerNight: 65,
    heroImage: 'https://images.unsplash.com/photo-1554223050-a25ddd61cdba?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1554223050-a25ddd61cdba?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 70',
      dinnerForTwo: '~USD 28',
      avgTemp: '8°C',
      airportDistance: '3 km · PUQ',
      currency: 'Peso Chileno / CLP',
    },
    keywords: ['intercambio de hogares en Patagonia', 'home exchange Torres del Paine', 'intercambiar casa en Patagonia chilena', 'alojamiento gratis Patagonia'],
  },

  // ── ARGENTINA ──────────────────────────────────────────────────────────
  'buenos-aires': {
    name: 'Buenos Aires',
    country: 'argentina',
    description: 'Buenos Aires es la capital más europea de América Latina: una metrópolis de barrios con personalidad propia, donde el tango nació en los conventillos de La Boca y donde la gastronomía fusiona el asado criollo con la cocina del mundo. Palermo, San Telmo, Recoleta y Puerto Madero ofrecen cada uno una experiencia diferente de la misma ciudad apasionada.',
    highlights: [
      'San Telmo y La Boca: tango en la calle y el Caminito colorido',
      'Palermo: parques, restaurantes de autor y vida nocturna',
      'Cementerio de Recoleta: arte y arquitectura entre mausoleos históricos',
      'Teatro Colón: uno de los teatros de ópera más importantes del mundo',
      'Puerto Madero: skyline moderno y restaurantes frente al Río de la Plata',
      'Feria de San Telmo: antigüedades y artesanías los domingos',
    ],
    bestSeason: 'Septiembre a noviembre y marzo a mayo — primavera y otoño con temperaturas perfectas.',
    avgPricePerNight: 45,
    heroImage: 'https://images.unsplash.com/photo-1612294037294-d8494f78f7d3?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1612294037294-d8494f78f7d3?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 50',
      dinnerForTwo: '~USD 20',
      avgTemp: '18°C',
      airportDistance: '35 km · EZE',
      currency: 'Peso Argentino / ARS',
    },
    keywords: ['intercambio de hogares en Buenos Aires', 'home exchange Buenos Aires', 'intercambiar casa en Buenos Aires', 'alojamiento gratis Buenos Aires Argentina'],
  },
  mendoza: {
    name: 'Mendoza',
    country: 'argentina',
    description: 'Mendoza es la capital del vino argentino y una de las ciudades más elegantes de Sudamérica. Rodeada por los viñedos de Malbec más cotizados del mundo y con el Aconcagua —el punto más alto de América— a pocas horas, es un destino que combina el enoturismo de alto nivel con la aventura en la montaña andina.',
    highlights: [
      'Ruta del Vino: bodegas Catena Zapata, Zuccardi, Achaval Ferrer',
      'Parque Provincial Aconcagua: base camp del pico más alto de América (6.961 m)',
      'Rafting en el río Mendoza: rápidos en el corazón de los Andes',
      'Termas de Cacheuta: aguas termales con vista a la cordillera',
      'Chacras de Coria y Luján de Cuyo: bodegas boutique y gastronomía de autor',
      'Ski en Las Leñas: la estación más glamorosa de Argentina',
    ],
    bestSeason: 'Enero a marzo para enoturismo (cosecha en febrero); julio a septiembre para esquí.',
    avgPricePerNight: 40,
    heroImage: 'https://images.unsplash.com/photo-1574523912076-b1b0c8b6a9f0?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1574523912076-b1b0c8b6a9f0?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 45',
      dinnerForTwo: '~USD 18',
      avgTemp: '18°C',
      airportDistance: '8 km · MDZ',
      currency: 'Peso Argentino / ARS',
    },
    keywords: ['intercambio de hogares en Mendoza', 'home exchange Mendoza', 'intercambiar casa en Mendoza', 'alojamiento gratis Mendoza Argentina'],
  },
  bariloche: {
    name: 'Bariloche',
    country: 'argentina',
    description: 'San Carlos de Bariloche es la Suiza latinoamericana: un destino de montaña que enamora todo el año con sus lagos cristalinos, bosques de lengas y la arquitectura de piedra y madera de su centro cívico. En invierno es el mayor resort de esquí del hemisferio sur; en verano, el paraíso del trekking y el kayak.',
    highlights: [
      'Cerro Catedral: el resort de ski más grande de Sudamérica',
      'Circuito Chico: lagos Nahuel Huapi, Moreno y Gutiérrez en auto o bici',
      'Trekking al Refugio Frey: uno de los más populares de la Patagonia',
      'Chocolate artesanal: Bariloche es la capital del chocolate argentino',
      'Parque Nacional Nahuel Huapi: senderos, kayak y fauna nativa',
      'Cruce de Lagos hacia Puerto Varas, Chile: travesía lacustre clásica',
    ],
    bestSeason: 'Julio a septiembre para ski; diciembre a febrero para deportes acuáticos y trekking.',
    avgPricePerNight: 55,
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 60',
      dinnerForTwo: '~USD 22',
      avgTemp: '9°C',
      airportDistance: '15 km · BRC',
      currency: 'Peso Argentino / ARS',
    },
    keywords: ['intercambio de hogares en Bariloche', 'home exchange Bariloche', 'intercambiar casa en Bariloche', 'alojamiento gratis Bariloche Argentina'],
  },
  cordoba: {
    name: 'Córdoba',
    country: 'argentina',
    description: 'Córdoba es la segunda ciudad de Argentina y la capital universitaria del país, con una energía joven y una gastronomía que mezcla lo criollo con influencias de la inmigración española e italiana. Las Sierras de Córdoba, a pocos minutos de la ciudad, ofrecen senderos, pueblos coloniales y paisajes de quebradas únicas.',
    highlights: [
      'Manzana Jesuítica: Patrimonio de la Humanidad UNESCO con la universidad más antigua del país',
      'Nueva Córdoba y Güemes: bares, galerías y vida nocturna universitaria',
      'Villa General Belgrano: pueblo de colonia alemana con festival de la cerveza',
      'Alta Gracia: la ciudad de Ernesto Che Guevara con museo y mansión jesuítica',
      'La Cumbrecita y Valle de Calamuchita: sierras, cascadas y arquitectura alpina',
      'Gastronomía cordobesa: la famosa milanesa napolitana y el bodegón criollo',
    ],
    bestSeason: 'Septiembre a noviembre y marzo a mayo — clima serrano ideal.',
    avgPricePerNight: 35,
    heroImage: 'https://images.unsplash.com/photo-1527320651455-d71abe1ac0f4?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1527320651455-d71abe1ac0f4?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 40',
      dinnerForTwo: '~USD 15',
      avgTemp: '18°C',
      airportDistance: '12 km · COR',
      currency: 'Peso Argentino / ARS',
    },
    keywords: ['intercambio de hogares en Córdoba', 'home exchange Córdoba Argentina', 'intercambiar casa en Córdoba', 'alojamiento gratis Córdoba Argentina'],
  },
  salta: {
    name: 'Salta',
    country: 'argentina',
    description: 'Salta, la Linda, es la puerta al noroeste argentino: una ciudad colonial bien conservada rodeada de paisajes cromáticos que van desde la Quebrada de Humahuaca hasta los salares de Jujuy. Su arquitectura colonial, sus empanadas con corte tucumano y el tren a las nubes la hacen uno de los destinos más singulares de Argentina.',
    highlights: [
      'Quebrada de Humahuaca: Patrimonio de la Humanidad con pueblos coloridos',
      'Tren a las Nubes: uno de los recorridos ferroviarios más altos del mundo',
      'Cafayate y los Valles Calchaquíes: vinos Torrontés y garganta del Diablo',
      'Cachi y Molinos: pueblos de adobe entre montañas de colores',
      'Mercado Artesanal: tejidos y artesanías de los pueblos originarios',
      'Purmamarca y el Cerro de los Siete Colores: postal icónica del norte argentino',
    ],
    bestSeason: 'Abril a octubre — temporada seca con días soleados y noches frescas.',
    avgPricePerNight: 38,
    heroImage: 'https://images.unsplash.com/photo-1623021399544-8d58c9e0c3a3?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1623021399544-8d58c9e0c3a3?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 45',
      dinnerForTwo: '~USD 15',
      avgTemp: '18°C',
      airportDistance: '9 km · SLA',
      currency: 'Peso Argentino / ARS',
    },
    keywords: ['intercambio de hogares en Salta', 'home exchange Salta Argentina', 'intercambiar casa en Salta', 'alojamiento gratis Salta Argentina'],
  },
  'patagonia-argentina': {
    name: 'Patagonia Argentina',
    country: 'argentina',
    description: 'La Patagonia argentina es inmensidad: la estepa infinita, los glaciares del Parque Los Glaciares, las ballenas de Península Valdés y los picos del Fitz Roy y el Chaltén. Es el destino para quienes buscan silencio, naturaleza virgen y la sensación de estar en el fin del mundo.',
    highlights: [
      'Perito Moreno: el glaciar más famoso del mundo que avanza y cruje',
      'El Chaltén y el Monte Fitz Roy: meca del trekking mundial',
      'Península Valdés: ballenas francas, orcas y pingüinos (Patrimonio UNESCO)',
      'Ushuaia: la ciudad más austral del mundo y Tierra del Fuego',
      'El Calafate: base para los glaciares del Parque Los Glaciares',
      'Ruta 40: la carretera mítica que atraviesa toda la Patagonia',
    ],
    bestSeason: 'Noviembre a marzo — verano austral con días largos y fauna activa.',
    avgPricePerNight: 60,
    heroImage: 'https://images.unsplash.com/photo-1557153888-1e39a11f54b5?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1557153888-1e39a11f54b5?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 65',
      dinnerForTwo: '~USD 25',
      avgTemp: '7°C',
      airportDistance: '2 km · FTE',
      currency: 'Peso Argentino / ARS',
    },
    keywords: ['intercambio de hogares en Patagonia Argentina', 'home exchange Patagonia', 'intercambiar casa en El Calafate', 'alojamiento gratis Patagonia Argentina'],
  },

  // ── COLOMBIA ───────────────────────────────────────────────────────────
  bogota: {
    name: 'Bogotá',
    country: 'colombia',
    description: 'Bogotá es una metrópolis de 8 millones de personas a 2.600 metros de altura, donde el arte callejero convive con museos de clase mundial y una escena gastronómica que está entre las mejores de América Latina. La Candelaria, el barrio colonial del centro, contrasta con la modernidad de Chapinero y Usaquén.',
    highlights: [
      'Museo del Oro: la colección de orfebrería precolombina más grande del mundo',
      'La Candelaria: barrio colonial con murales de arte urbano',
      'Monserrate: cerro sagrado con vista panorámica a toda la ciudad',
      'Usaquén: mercado artesanal dominical y restaurantes de chef',
      'Ciclovía dominical: 120 km de vías cerradas al tráfico para ciclistas y peatones',
      'Gastronomía: ajiaco santafereño, fritanga y cocina de autor en el Parque de la 93',
    ],
    bestSeason: 'Diciembre a marzo y julio a agosto — las dos temporadas secas del año.',
    avgPricePerNight: 35,
    heroImage: 'https://images.unsplash.com/photo-1509909756405-be0199881695?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1509909756405-be0199881695?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 45',
      dinnerForTwo: '~USD 15',
      avgTemp: '14°C',
      airportDistance: '14 km · BOG',
      currency: 'Peso Colombiano / COP',
    },
    keywords: ['intercambio de hogares en Bogotá', 'home exchange Bogotá', 'intercambiar casa en Bogotá', 'alojamiento gratis Bogotá Colombia'],
  },
  medellin: {
    name: 'Medellín',
    country: 'colombia',
    description: 'Medellín es la ciudad de la eterna primavera y uno de los casos de transformación urbana más estudiados del mundo. El Metrocable conecta comunas antes aisladas con el centro, el arte de Botero llena plazas públicas y el barrio El Poblado concentra una escena gastronómica y cultural que seduce a viajeros de todo el mundo.',
    highlights: [
      'El Poblado y Parque Lleras: restaurantes, bares y vida nocturna',
      'Plaza Botero: 23 esculturas del maestro Fernando Botero',
      'Metrocable y Parque Arví: bosque nativo accesible desde el metro',
      'Guatapé y La Piedra del Peñol: escalada al peñasco con vista de 360°',
      'Jardín Botánico Joaquín Antonio Uribe: orquídeas y mariposas',
      'Feria de las Flores (agosto): desfile de silleteros, tradición patrimonio',
    ],
    bestSeason: 'Todo el año (clima primaveral de 22°C promedio). Diciembre y agosto tienen fiestas importantes.',
    avgPricePerNight: 38,
    heroImage: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 40',
      dinnerForTwo: '~USD 12',
      avgTemp: '22°C',
      airportDistance: '35 km · MDE',
      currency: 'Peso Colombiano / COP',
    },
    keywords: ['intercambio de hogares en Medellín', 'home exchange Medellín', 'intercambiar casa en Medellín', 'alojamiento gratis Medellín Colombia'],
  },
  cartagena: {
    name: 'Cartagena',
    country: 'colombia',
    description: 'Cartagena de Indias es una ciudad amurallada que guarda siglos de historia colonial a orillas del Mar Caribe. Sus calles empedradas, sus balcones floridos y sus plazas de bougainvilleas son el telón de fondo de una gastronomía caribeña extraordinaria y de playas cristalinas en las islas del Rosario.',
    highlights: [
      'Ciudad Amurallada: Patrimonio de la Humanidad con murallas del siglo XVI',
      'Castillo San Felipe de Barajas: fortaleza colonial sobre cerro con túneles',
      'Islas del Rosario: arrecifes de coral y aguas turquesas a 35 km',
      'Barrio Getsemaní: arte callejero y la bohemia más auténtica de la ciudad',
      'Playa de Bocagrande y Bocachica: playas urbanas frente al Caribe',
      'Gastronomía caribeña: ceviche de camarón, arroz con coco y patacón',
    ],
    bestSeason: 'Diciembre a abril — temporada seca caribeña con brisa constante.',
    avgPricePerNight: 55,
    heroImage: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 60',
      dinnerForTwo: '~USD 20',
      avgTemp: '29°C',
      airportDistance: '5 km · CTG',
      currency: 'Peso Colombiano / COP',
    },
    keywords: ['intercambio de hogares en Cartagena', 'home exchange Cartagena Colombia', 'intercambiar casa en Cartagena', 'alojamiento gratis Cartagena Colombia'],
  },
  cali: {
    name: 'Cali',
    country: 'colombia',
    description: 'Cali es la capital mundial de la salsa y la ciudad más vibrante del Pacífico colombiano. Sus barrios como San Antonio conservan la arquitectura colonial, mientras que el Barrio Granada y Menga se llenan de ritmo hasta el amanecer. El Valle del Cauca circundante ofrece haciendas cañeras e ingenios coloniales.',
    highlights: [
      'Barrio San Antonio: iglesias coloniales, cafés y vista a la ciudad',
      'Salsa en el Tin Tin Deo y Zaperoco: bailar salsa caleña con los locales',
      'Zoológico de Cali: uno de los más biodiversos de Sudamérica',
      'Iglesia de La Merced: la más antigua de Colombia en pie',
      'Hacienda El Paraíso: escenario de la novela María en el Valle del Cauca',
      'Festival Mundial de Salsa (diciembre): miles de bailarines en competencia',
    ],
    bestSeason: 'Junio a agosto y diciembre a febrero — temporadas secas.',
    avgPricePerNight: 30,
    heroImage: 'https://images.unsplash.com/photo-1576875231573-06b78e3d3cc9?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1576875231573-06b78e3d3cc9?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 35',
      dinnerForTwo: '~USD 10',
      avgTemp: '24°C',
      airportDistance: '20 km · CLO',
      currency: 'Peso Colombiano / COP',
    },
    keywords: ['intercambio de hogares en Cali', 'home exchange Cali Colombia', 'intercambiar casa en Cali', 'alojamiento gratis Cali Colombia'],
  },
  'eje-cafetero': {
    name: 'Eje Cafetero',
    country: 'colombia',
    description: 'El Eje Cafetero, Paisaje Cultural Cafetero Patrimonio de la Humanidad, es la región que le da al mundo el café colombiano más fino. Sus pueblos de tapia pisada con balcones de madera tallada —Salento, Filandia, Jardín— y los valles verdes del Quindío ofrecen una inmersión total en la cultura cafetera y la biodiversidad del Trópico Andino.',
    highlights: [
      'Valle de Cocora: palmas de cera (árbol nacional) en niebla andina',
      'Salento: el pueblo más pintoresco del Eje con artesanías y trucha',
      'Finca cafetera tradicional: recolección y proceso del café de origen',
      'Mariposario del Bosque: 50 especies de mariposas nativas',
      'Parque Nacional Natural Los Nevados: volcanes nevados y lagunas de altura',
      'Filandia y Jardín: arquitectura republicana y mirador de guadua',
    ],
    bestSeason: 'Diciembre a febrero y junio a agosto — temporadas secas de la región andina.',
    avgPricePerNight: 32,
    heroImage: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 35',
      dinnerForTwo: '~USD 12',
      avgTemp: '19°C',
      airportDistance: '30 km · AXM',
      currency: 'Peso Colombiano / COP',
    },
    keywords: ['intercambio de hogares en Eje Cafetero', 'home exchange Eje Cafetero', 'intercambiar casa en Salento', 'alojamiento gratis Eje Cafetero Colombia'],
  },
  'santa-marta': {
    name: 'Santa Marta',
    country: 'colombia',
    description: 'Santa Marta es la ciudad más antigua de América del Sur que ha sobrevivido sin interrupción, y combina una bahía caribeña espectacular con la Sierra Nevada de Santa Marta, la montaña costera más alta del mundo. Es la puerta al Parque Nacional Tayrona y al trekking hacia la Ciudad Perdida de los Tayronas.',
    highlights: [
      'Parque Nacional Natural Tayrona: selva tropical hasta playas del Caribe',
      'Ciudad Perdida (Teyuna): trekking de 4 días a la ciudad precolombina en la sierra',
      'Playa de Taganga: bahía de pescadores con snorkel y buceo asequible',
      'El Rodadero: la playa más popular con paseos en lancha y actividades',
      'Quinta de San Pedro Alejandrino: museo donde murió Simón Bolívar',
      'Minca: pueblo de montaña cafetera a 30 minutos con cascadas y avistamiento de aves',
    ],
    bestSeason: 'Diciembre a abril — temporada seca caribeña.',
    avgPricePerNight: 40,
    heroImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 50',
      dinnerForTwo: '~USD 15',
      avgTemp: '30°C',
      airportDistance: '16 km · SMR',
      currency: 'Peso Colombiano / COP',
    },
    keywords: ['intercambio de hogares en Santa Marta', 'home exchange Santa Marta Colombia', 'intercambiar casa en Santa Marta', 'alojamiento gratis Santa Marta Colombia'],
  },

  // ── MÉXICO ─────────────────────────────────────────────────────────────
  'ciudad-de-mexico': {
    name: 'Ciudad de México',
    country: 'mexico',
    description: 'La Ciudad de México es una de las megalópolis más apasionantes del planeta: 20 millones de personas, una gastronomía declarada Patrimonio de la Humanidad, museos que rivalizan con los mejores del mundo y barrios como Roma, Condesa o Coyoacán que reinventan la vida urbana latinoamericana.',
    highlights: [
      'Centro Histórico: Zócalo, Catedral Metropolitana y Templo Mayor azteca',
      'Xochimilco: trajineras en los canales prehispánicos del sur',
      'Museo Nacional de Antropología: la colección arqueológica más importante de México',
      'Frida Kahlo Museum en Coyoacán: la Casa Azul de la pintora más icónica del país',
      'Mercado de Jamaica y Mercado de la Merced: la ciudad en su expresión más viva',
      'Roma Norte y Condesa: gastronomía de autor, parques art-decó y cafeterías',
    ],
    bestSeason: 'Noviembre a mayo — temporada seca con cielos despejados.',
    avgPricePerNight: 45,
    heroImage: 'https://images.unsplash.com/photo-1548550231-3d06bf7dced3?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1548550231-3d06bf7dced3?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 55',
      dinnerForTwo: '~USD 20',
      avgTemp: '17°C',
      airportDistance: '15 km · AICM',
      currency: 'Peso Mexicano / MXN',
    },
    keywords: ['intercambio de hogares en Ciudad de México', 'home exchange CDMX', 'intercambiar casa en Ciudad de México', 'alojamiento gratis CDMX México'],
  },
  guadalajara: {
    name: 'Guadalajara',
    country: 'mexico',
    description: 'Guadalajara, la Perla del Occidente, es la cuna del mariachi, el tequila y la charrería. Segunda ciudad de México, combina un centro histórico barroco monumental con barrios modernos como Tlaquepaque y Zapopan, y es el epicentro tecnológico del país, con el Valle del Silicio Mexicano.',
    highlights: [
      'Centro Histórico: la Catedral, el Hospicio Cabañas (UNESCO) y el Teatro Degollado',
      'Tlaquepaque: artesanías, talavera y gastronomía regional en calles empedradas',
      'Tequila: el pueblo del Agave Azul a 60 km con recorrido por destilerías',
      'Lago de Chapala: el lago más grande de México a 45 minutos',
      'Mercado de San Juan de Dios: el mayor mercado cubierto de América Latina',
      'Festival Internacional de Cine de Guadalajara (marzo)',
    ],
    bestSeason: 'Octubre a mayo — clima templado y sin lluvias.',
    avgPricePerNight: 40,
    heroImage: 'https://images.unsplash.com/photo-1586449480537-3a1d9f4d5a32?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1586449480537-3a1d9f4d5a32?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 50',
      dinnerForTwo: '~USD 18',
      avgTemp: '20°C',
      airportDistance: '17 km · GDL',
      currency: 'Peso Mexicano / MXN',
    },
    keywords: ['intercambio de hogares en Guadalajara', 'home exchange Guadalajara México', 'intercambiar casa en Guadalajara', 'alojamiento gratis Guadalajara México'],
  },
  oaxaca: {
    name: 'Oaxaca',
    country: 'mexico',
    description: 'Oaxaca es la capital cultural y gastronómica de México: sus mercados huelen a copal y chocolate, su mezcal artesanal es Patrimonio Inmaterial y sus sitios arqueológicos zapotecos de Monte Albán dominan el valle desde las montañas. La fusión de tradiciones indígenas y arte contemporáneo la hace irresistible.',
    highlights: [
      'Monte Albán: ciudad zapoteca del siglo V a.C. declarada Patrimonio UNESCO',
      'Mercado Benito Juárez y Mercado 20 de Noviembre: mole, tlayudas y chapulines',
      'Mezcal artesanal en Matatlán: el pueblo del mezcal con palenques tradicionales',
      'Hierve el Agua: cascadas petrificadas con piscinas naturales de agua mineral',
      'Día de Muertos (noviembre): la celebración más auténtica y viva del país',
      'Museo de las Culturas de Oaxaca: joyería mixteca y códices precolombinos',
    ],
    bestSeason: 'Octubre a mayo — temporada seca. Noviembre es especial por el Día de Muertos.',
    avgPricePerNight: 48,
    heroImage: 'https://images.unsplash.com/photo-1591710668263-64bb2c677827?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1591710668263-64bb2c677827?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 55',
      dinnerForTwo: '~USD 18',
      avgTemp: '20°C',
      airportDistance: '7 km · OAX',
      currency: 'Peso Mexicano / MXN',
    },
    keywords: ['intercambio de hogares en Oaxaca', 'home exchange Oaxaca México', 'intercambiar casa en Oaxaca', 'alojamiento gratis Oaxaca México'],
  },
  'san-miguel-de-allende': {
    name: 'San Miguel de Allende',
    country: 'mexico',
    description: 'San Miguel de Allende es la ciudad más bonita de México según numerosos rankings internacionales: sus calles de adoquín, la parroquia de La Santa Casa de Loreto y el ambiente artístico que atrae a creadores de todo el mundo la convierten en un destino romántico y sofisticado en el corazón del Bajío.',
    highlights: [
      'Parroquia de San Miguel Arcángel: la catedral neogótica más fotografiada de México',
      'El Jardín: la plaza central más animada del Bajío con cafés y galerías',
      'Instituto Allende: escuelas de arte que atrajeron a artistas desde los años 50',
      'Guanajuato: ciudad minera colonial declarada Patrimonio UNESCO a 1 hora',
      'Festival Internacional de Jazz y Blues (agosto)',
      'Gastronomía de autor: San Miguel está entre los mejores destinos gastronómicos de México',
    ],
    bestSeason: 'Noviembre a mayo — temporada seca con noches frescas.',
    avgPricePerNight: 60,
    heroImage: 'https://images.unsplash.com/photo-1574724003839-28ca80cc2e48?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1574724003839-28ca80cc2e48?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 70',
      dinnerForTwo: '~USD 25',
      avgTemp: '18°C',
      airportDistance: '90 km · GTO',
      currency: 'Peso Mexicano / MXN',
    },
    keywords: ['intercambio de hogares en San Miguel de Allende', 'home exchange San Miguel de Allende', 'intercambiar casa en San Miguel de Allende', 'alojamiento gratis San Miguel Allende México'],
  },
  tulum: {
    name: 'Tulum',
    country: 'mexico',
    description: 'Tulum combina la magia de las ruinas mayas sobre acantilados frente al Mar Caribe con cenotes de agua dulce ocultos en la selva y una escena de bienestar y gastronomía que la ha convertido en el destino más trendy de México. La Riviera Maya y el Parque Nacional de Sian Ka\'an rodean este rincón único.',
    highlights: [
      'Zona Arqueológica de Tulum: templos mayas frente al Caribe turquesa',
      'Cenotes: Dos Ojos, Gran Cenote, Cenote Calavera — buceo en agua cristalina',
      'Playa Paraíso y Playa Ruinas: las playas más bellas de la Riviera Maya',
      'Sian Ka\'an Biosphere Reserve: lagunas, manglares y delfines (Patrimonio UNESCO)',
      'Cobá: pirámide maya de 42 m en la selva, a 45 minutos',
      'Gastronomía orgánica y wellness: la escena de restaurantes de autor más sofisticada del Caribe mexicano',
    ],
    bestSeason: 'Noviembre a abril — temporada seca caribeña con agua calmada.',
    avgPricePerNight: 75,
    heroImage: 'https://images.unsplash.com/photo-1552074284-5e84a2e9de1f?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1552074284-5e84a2e9de1f?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 80',
      dinnerForTwo: '~USD 30',
      avgTemp: '29°C',
      airportDistance: '130 km · CUN',
      currency: 'Peso Mexicano / MXN',
    },
    keywords: ['intercambio de hogares en Tulum', 'home exchange Tulum México', 'intercambiar casa en Tulum', 'alojamiento gratis Tulum México'],
  },
  merida: {
    name: 'Mérida',
    country: 'mexico',
    description: 'Mérida, la Ciudad Blanca, es la capital cultural de la Península de Yucatán y la ciudad más segura de México. Desde aquí se accede a las zonas arqueológicas mayas más importantes del mundo —Chichén Itzá, Uxmal, Kabah— y a los cenotes y playas del Golfo de México a 40 minutos.',
    highlights: [
      'Chichén Itzá: la pirámide maya Maravilla del Mundo Moderno, a 2 horas',
      'Uxmal: ciudad maya del Puuc, declarada Patrimonio UNESCO',
      'Progreso y Celestún: playas del Golfo y reserva de flamencos rosas',
      'Centro Histórico: haciendas coloniales reconvertidas en hoteles de lujo',
      'Mérida en Domingo: el Paseo de Montejo cerrado y música yucateca gratis',
      'Gastronomía yucateca: cochinita pibil, papadzules y queso de bola',
    ],
    bestSeason: 'Noviembre a abril — calor moderado y baja humedad.',
    avgPricePerNight: 42,
    heroImage: 'https://images.unsplash.com/photo-1591553161875-1ce4db4f9b22?w=1920&q=80&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1591553161875-1ce4db4f9b22?w=600&h=400&q=70&auto=format&fit=crop',
    stats: {
      hotelAvgPerNight: '~USD 50',
      dinnerForTwo: '~USD 18',
      avgTemp: '30°C',
      airportDistance: '9 km · MID',
      currency: 'Peso Mexicano / MXN',
    },
    keywords: ['intercambio de hogares en Mérida', 'home exchange Mérida México', 'intercambiar casa en Mérida', 'alojamiento gratis Mérida México Yucatán'],
  },
}

// Lookup inverso: slug → nombre canónico de la ciudad
export const CITY_SLUG_TO_NAME = Object.fromEntries(
  Object.entries(cityData).map(([slug, data]) => [slug, data.name])
)

// Todas las ciudades objetivo por país (slug → country slug)
export const TARGET_CITIES_BY_COUNTRY = Object.entries(cityData).reduce((acc, [slug, data]) => {
  if (!acc[data.country]) acc[data.country] = []
  acc[data.country].push(slug)
  return acc
}, {})
