// ─── LOCALIDADES RUKKA — Todas las regiones y comunas de Chile ────────────────

export const REGIONES_RUKKA = [
  {
    id: 'arica-parinacota',
    nombre: 'Región de Arica y Parinacota',
    comunas: ['Arica', 'Camarones', 'Putre', 'General Lagos'],
  },
  {
    id: 'tarapaca',
    nombre: 'Región de Tarapacá',
    comunas: ['Iquique', 'Alto Hospicio', 'Pozo Almonte', 'Camiña', 'Colchane', 'Huara', 'Pica'],
  },
  {
    id: 'antofagasta',
    nombre: 'Región de Antofagasta',
    comunas: ['Antofagasta', 'Mejillones', 'Sierra Gorda', 'Taltal', 'Calama', 'Ollagüe', 'San Pedro de Atacama', 'Tocopilla', 'María Elena'],
  },
  {
    id: 'atacama',
    nombre: 'Región de Atacama',
    comunas: ['Copiapó', 'Caldera', 'Tierra Amarilla', 'Chañaral', 'Diego de Almagro', 'Vallenar', 'Alto del Carmen', 'Freirina', 'Huasco'],
  },
  {
    id: 'coquimbo',
    nombre: 'Región de Coquimbo',
    comunas: ['La Serena', 'Coquimbo', 'Andacollo', 'La Higuera', 'Paihuano', 'Vicuña', 'Illapel', 'Canela', 'Los Vilos', 'Salamanca', 'Ovalle', 'Combarbalá', 'Monte Patria', 'Punitaqui', 'Río Hurtado'],
  },
  {
    id: 'valparaiso',
    nombre: 'Región de Valparaíso',
    comunas: ['Valparaíso', 'Casablanca', 'Concón', 'Juan Fernández', 'Puchuncaví', 'Quintero', 'Viña del Mar', 'Isla de Pascua', 'Los Andes', 'Calle Larga', 'Rinconada', 'San Esteban', 'La Ligua', 'Cabildo', 'Papudo', 'Petorca', 'Zapallar', 'Quillota', 'Calera', 'Hijuelas', 'La Cruz', 'Nogales', 'San Antonio', 'Algarrobo', 'Cartagena', 'El Quisco', 'El Tabo', 'Santo Domingo', 'San Felipe', 'Catemu', 'Llaillay', 'Panquehue', 'Putaendo', 'Santa María', 'Quilpué', 'Limache', 'Olmué', 'Villa Alemana'],
  },
  {
    id: 'metropolitana',
    nombre: 'Región Metropolitana de Santiago',
    comunas: ['Santiago', 'Cerrillos', 'Cerro Navia', 'Conchalí', 'El Bosque', 'Estación Central', 'Huechuraba', 'Independencia', 'La Cisterna', 'La Florida', 'La Granja', 'La Pintana', 'La Reina', 'Las Condes', 'Lo Barnechea', 'Lo Espejo', 'Lo Prado', 'Macul', 'Maipú', 'Ñuñoa', 'Pedro Aguirre Cerda', 'Peñalolén', 'Providencia', 'Pudahuel', 'Quilicura', 'Quinta Normal', 'Recoleta', 'Renca', 'San Joaquín', 'San Miguel', 'San Ramón', 'Vitacura', 'Puente Alto', 'Pirque', 'San José de Maipo', 'Colina', 'Lampa', 'Tiltil', 'San Bernardo', 'Buin', 'Calera de Tango', 'Paine', 'Melipilla', 'Alhué', 'Curacaví', 'María Pinto', 'San Pedro', 'Talagante', 'El Monte', 'Isla de Maipo', 'Padre Hurtado', 'Peñaflor'],
  },
  {
    id: 'ohiggins',
    nombre: "Región del Libertador Gral. Bernardo O'Higgins",
    comunas: ['Rancagua', 'Codegua', 'Coinco', 'Coltauco', 'Doñihue', 'Graneros', 'Las Cabras', 'Machalí', 'Malloa', 'Mostazal', 'Olivar', 'Peumo', 'Pichidegua', 'Quinta de Tilcoco', 'Rengo', 'Requínoa', 'San Vicente', 'Pichilemu', 'La Estrella', 'Litueche', 'Marchihue', 'Navidad', 'Paredones', 'San Fernando', 'Chépica', 'Chimbarongo', 'Lolol', 'Nancagua', 'Palmilla', 'Peralillo', 'Placilla', 'Pumanque', 'Santa Cruz', 'Puertecillo', 'Matanzas'],
  },
  {
    id: 'maule',
    nombre: 'Región del Maule',
    comunas: ['Talca', 'Constitución', 'Curepto', 'Empedrado', 'Maule', 'Pelarco', 'Pencahue', 'Río Claro', 'San Clemente', 'San Rafael', 'Cauquenes', 'Chanco', 'Pelluhue', 'Curicó', 'Hualañé', 'Licantén', 'Molina', 'Rauco', 'Romeral', 'Sagrada Familia', 'Teno', 'Vichuquén', 'Linares', 'Colbún', 'Longaví', 'Parral', 'Retiro', 'San Javier', 'Villa Alegre', 'Yerbas Buenas'],
  },
  {
    id: 'nuble',
    nombre: 'Región de Ñuble',
    comunas: ['Chillán', 'Bulnes', 'Cobquecura', 'Coelemu', 'Coihueco', 'Chillán Viejo', 'El Carmen', 'Ninhue', 'Ñiquén', 'Pemuco', 'Pinto', 'Portezuelo', 'Quillón', 'Quirihue', 'Ránquil', 'San Carlos', 'San Fabián', 'San Ignacio', 'San Nicolás', 'Treguaco', 'Yungay'],
  },
  {
    id: 'biobio',
    nombre: 'Región del Biobío',
    comunas: ['Concepción', 'Coronel', 'Chiguayante', 'Florida', 'Hualqui', 'Lota', 'Penco', 'San Pedro de la Paz', 'Santa Juana', 'Talcahuano', 'Tomé', 'Hualpén', 'Lebu', 'Arauco', 'Cañete', 'Contulmo', 'Curanilahue', 'Los Álamos', 'Tirúa', 'Los Ángeles', 'Antuco', 'Cabrero', 'Laja', 'Mulchén', 'Nacimiento', 'Negrete', 'Quilaco', 'Quilleco', 'San Rosendo', 'Santa Bárbara', 'Tucapel', 'Yumbel', 'Alto Biobío'],
  },
  {
    id: 'araucania',
    nombre: 'Región de La Araucanía',
    comunas: ['Temuco', 'Carahue', 'Cunco', 'Curarrehue', 'Freire', 'Galvarino', 'Gorbea', 'Lautaro', 'Loncoche', 'Melipeuco', 'Nueva Imperial', 'Padre Las Casas', 'Perquenco', 'Pitrufquén', 'Pucón', 'Saavedra', 'Teodoro Schmidt', 'Toltén', 'Vilcún', 'Villarrica', 'Cholchol', 'Angol', 'Collipulli', 'Curacautín', 'Ercilla', 'Lonquimay', 'Los Sauces', 'Lumaco', 'Purén', 'Renaico', 'Traiguén', 'Victoria'],
  },
  {
    id: 'los-rios',
    nombre: 'Región de Los Ríos',
    comunas: ['Valdivia', 'Corral', 'Futrono', 'La Unión', 'Lago Ranco', 'Lanco', 'Los Lagos', 'Máfil', 'Mariquina', 'Paillaco', 'Panguipulli', 'Río Bueno'],
  },
  {
    id: 'los-lagos',
    nombre: 'Región de Los Lagos',
    comunas: ['Puerto Montt', 'Calbuco', 'Cochamó', 'Fresia', 'Frutillar', 'Los Muermos', 'Llanquihue', 'Maullín', 'Puerto Varas', 'Castro', 'Ancud', 'Chonchi', 'Curaco de Vélez', 'Dalcahue', 'Puqueldón', 'Queilén', 'Quellón', 'Quemchi', 'Quinchao', 'Osorno', 'Puerto Octay', 'Purranque', 'Puyehue', 'Río Negro', 'San Juan de la Costa', 'San Pablo', 'Chaitén', 'Futaleufú', 'Hualaihué', 'Palena'],
  },
  {
    id: 'aysen',
    nombre: 'Región de Aysén del Gral. Carlos Ibáñez del Campo',
    comunas: ['Coyhaique', 'Lago Verde', 'Aysén', 'Cisnes', 'Guaitecas', 'Cochrane', "O'Higgins", 'Tortel', 'Chile Chico', 'Río Ibáñez'],
  },
  {
    id: 'magallanes',
    nombre: 'Región de Magallanes y de la Antártica Chilena',
    comunas: ['Punta Arenas', 'Laguna Blanca', 'Río Verde', 'San Gregorio', 'Cabo de Hornos', 'Antártica', 'Porvenir', 'Primavera', 'Timaukel', 'Puerto Natales', 'Torres del Paine'],
  },
]

// Lista plana de todas las comunas disponibles
export const COMUNAS_RUKKA = REGIONES_RUKKA.flatMap(r => r.comunas).sort()

// Destinos destacados con metadata visual para tarjetas, banners y hero
export const DESTINOS_RUKKA = [
  {
    id: 'zapallar',
    city: 'Zapallar',
    region: 'Región de Valparaíso',
    tipo: 'Playa',
    tagline: 'Elegancia frente al mar',
    description: 'El balneario más exclusivo de Chile. Caleta íntima, vegetación exuberante y mar cristalino.',
    image: 'https://images.unsplash.com/photo-1628048373575-ab3f2a663985?w=800&q=80',
    color: '#134e4a',
    accent: '#2dd4bf',
    emoji: '🌺',
    tags: ['Playa', 'Relax', 'Gastronomía'],
  },
  {
    id: 'cachagua',
    city: 'Cachagua',
    region: 'Región de Valparaíso',
    tipo: 'Playa',
    tagline: 'La playa más secreta del litoral',
    description: 'Reserva natural, pingüinos de Humboldt y una playa protegida que enamora a quienes la descubren.',
    image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80',
    color: '#0c4a6e',
    accent: '#7dd3fc',
    emoji: '🐧',
    tags: ['Playa', 'Naturaleza', 'Tranquilidad'],
  },
  {
    id: 'papudo',
    city: 'Papudo',
    region: 'Región de Valparaíso',
    tipo: 'Playa',
    tagline: 'El balneario más pintoresco',
    description: 'Caleta de pescadores, playas tranquilas y aire puro en la costa norte de Valparaíso.',
    image: 'https://images.unsplash.com/photo-1628048460441-633a59962c5e?w=800&q=80',
    color: '#0c4a6e',
    accent: '#38bdf8',
    emoji: '⚓',
    tags: ['Playa', 'Tranquilidad', 'Familia'],
  },
  {
    id: 'santo-domingo',
    city: 'Santo Domingo',
    region: 'Región de Valparaíso',
    tipo: 'Playa',
    tagline: 'Arena blanca y olas perfectas',
    description: 'Playas vírgenes, dunas y el mejor borde costero del litoral central de Chile.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    color: '#0369a1',
    accent: '#7dd3fc',
    emoji: '🏖️',
    tags: ['Playa', 'Dunas', 'Surf'],
  },
  {
    id: 'pichilemu',
    city: 'Pichilemu',
    region: "Región del Libertador Gral. Bernardo O'Higgins",
    tipo: 'Playa / Surf',
    tagline: 'Las olas te esperan',
    description: 'Capital del surf en Chile. Punta de Lobos, atardeceres de película y brisa de mar todo el año.',
    image: 'https://images.unsplash.com/photo-1582142894463-cfa81bf9083c?w=800&q=80',
    color: '#0f3460',
    accent: '#4ade80',
    emoji: '🏄',
    tags: ['Surf', 'Playa', 'Aventura'],
  },
  {
    id: 'puertecillo',
    city: 'Puertecillo',
    region: "Región del Libertador Gral. Bernardo O'Higgins",
    tipo: 'Playa / Surf',
    tagline: 'El secreto del surf chileno',
    description: 'Olas de clase mundial, acantilados salvajes y una comunidad de surfistas que guardan celosamente su paraíso.',
    image: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&q=80',
    color: '#1e3a5f',
    accent: '#4ade80',
    emoji: '🤙',
    tags: ['Surf', 'Playa', 'Aventura'],
  },
  {
    id: 'navidad',
    city: 'Navidad',
    region: "Región del Libertador Gral. Bernardo O'Higgins",
    tipo: 'Playa',
    tagline: 'Costa salvaje del Pacífico',
    description: 'Acantilados, playas solitarias y el oleaje más poderoso del litoral central. Naturaleza sin filtros.',
    image: 'https://images.unsplash.com/photo-1476900543704-4312b78632f8?w=800&q=80',
    color: '#1e3a5f',
    accent: '#60a5fa',
    emoji: '🌊',
    tags: ['Playa', 'Naturaleza', 'Tranquilidad'],
  },
  {
    id: 'matanzas',
    city: 'Matanzas',
    region: "Región del Libertador Gral. Bernardo O'Higgins",
    tipo: 'Playa / Naturaleza',
    tagline: 'El viento libre de Matanzas',
    description: 'Paraíso del kitesurf y windsurf. Vientos constantes, acantilados imponentes y playas casi deshabitadas.',
    image: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=800&q=80',
    color: '#1a3c5e',
    accent: '#38bdf8',
    emoji: '🪁',
    tags: ['Kitesurf', 'Playa', 'Naturaleza'],
  },
  {
    id: 'pucon',
    city: 'Pucón',
    region: 'Región de La Araucanía',
    tipo: 'Lago / Volcán',
    tagline: 'Aventura en el corazón de La Araucanía',
    description: 'Volcán Villarrica, aguas termales, rafting y el lago más hermoso del sur de Chile.',
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80',
    color: '#1c3d1c',
    accent: '#86efac',
    emoji: '🌋',
    tags: ['Aventura', 'Lago', 'Naturaleza'],
  },
  {
    id: 'puerto-varas',
    city: 'Puerto Varas',
    region: 'Región de Los Lagos',
    tipo: 'Lago / Montaña',
    tagline: 'La ciudad de las rosas',
    description: 'Con vista al volcán Osorno y el lago Llanquihue, la ciudad más bella del sur austral.',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    color: '#1a3055',
    accent: '#93c5fd',
    emoji: '🌹',
    tags: ['Lago', 'Montaña', 'Gastronomía'],
  },
  {
    id: 'san-pedro-de-atacama',
    city: 'San Pedro de Atacama',
    region: 'Región de Antofagasta',
    tipo: 'Desierto / Cultura',
    tagline: 'El desierto más árido del mundo',
    description: 'Valle de la Luna, géiseres del Tatio, lagunas altiplánicas y el cielo más estrellado de la Tierra.',
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80',
    color: '#78350f',
    accent: '#fcd34d',
    emoji: '🌵',
    tags: ['Desierto', 'Cultura', 'Astroturismo'],
  },
  {
    id: 'la-serena',
    city: 'La Serena',
    region: 'Región de Coquimbo',
    tipo: 'Playa / Ciudad',
    tagline: 'La ciudad de las iglesias',
    description: 'Playas extensas, cielos despejados para la astronomía y la arquitectura colonial más bella del norte chico.',
    image: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=800&q=80',
    color: '#1e3a5f',
    accent: '#fbbf24',
    emoji: '🔭',
    tags: ['Playa', 'Astronomía', 'Ciudad'],
  },
  {
    id: 'torres-del-paine',
    city: 'Torres del Paine',
    region: 'Región de Magallanes y de la Antártica Chilena',
    tipo: 'Trekking / Naturaleza',
    tagline: 'El fin del mundo te llama',
    description: 'Glaciares, cóndores, guanacos y las torres más imponentes del planeta. Trekking de clase mundial.',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
    color: '#0f2744',
    accent: '#67e8f9',
    emoji: '🏔️',
    tags: ['Trekking', 'Glaciares', 'Naturaleza'],
  },
  {
    id: 'vina-del-mar',
    city: 'Viña del Mar',
    region: 'Región de Valparaíso',
    tipo: 'Playa / Ciudad',
    tagline: 'La ciudad jardín',
    description: 'Casino, playas urbanas, el festival de la canción y la vida nocturna más vibrante de Chile.',
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
    color: '#0c4a6e',
    accent: '#f472b6',
    emoji: '🌸',
    tags: ['Playa', 'Ciudad', 'Entretenimiento'],
  },
]

// ── Helpers ───────────────────────────────────────────────────────────────────

export function getComunasByRegion(regionNombre) {
  const region = REGIONES_RUKKA.find(r => r.nombre === regionNombre)
  return region?.comunas ?? []
}

export function getAllComunas() {
  return COMUNAS_RUKKA
}

export function getDestinoByCity(city) {
  return DESTINOS_RUKKA.find(d => d.city.toLowerCase() === city.toLowerCase())
}
