// geo: banner datasets per supported country for hero rotation

export const COUNTRY_BANNERS = {
  CL: [
    {
      id: 'zapallar',
      city: 'Zapallar',
      tipo: 'Playa',
      tagline: 'Elegancia frente al mar',
      description: 'El balneario más exclusivo de Chile. Caleta íntima, vegetación exuberante y mar cristalino.',
      image: 'https://images.unsplash.com/photo-1628048373575-ab3f2a663985?w=1600&q=80',
      color: '#134e4a',
      emoji: '🌺',
      tags: ['Playa', 'Relax', 'Gastronomía'],
    },
    {
      id: 'pichilemu',
      city: 'Pichilemu',
      tipo: 'Surf',
      tagline: 'Las olas te esperan',
      description: 'Capital del surf en Chile. Punta de Lobos, atardeceres de película y brisa de mar.',
      image: 'https://images.unsplash.com/photo-1582142894463-cfa81bf9083c?w=1600&q=80',
      color: '#0f3460',
      emoji: '🏄',
      tags: ['Surf', 'Playa', 'Aventura'],
    },
    {
      id: 'puerto-varas',
      city: 'Puerto Varas',
      tipo: 'Lago / Montaña',
      tagline: 'El lago azul y el volcán perfecto',
      description: 'Casas con vista al Lago Llanquihue y al Osorno. La Patagonia en su versión más acogedora.',
      image: 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=1600&q=80',
      color: '#1e3a5f',
      emoji: '🌋',
      tags: ['Lago', 'Montaña', 'Naturaleza'],
    },
    {
      id: 'san-pedro',
      city: 'San Pedro de Atacama',
      tipo: 'Desierto',
      tagline: 'Donde el cielo empieza',
      description: 'El desierto más árido del mundo, el cielo estrellado más limpio y geiseres al amanecer.',
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80',
      color: '#78350f',
      emoji: '🌵',
      tags: ['Desierto', 'Astroturismo', 'Aventura'],
    },
    {
      id: 'valparaiso',
      city: 'Valparaíso',
      tipo: 'Puerto / Arte',
      tagline: 'El cerro que enamora',
      description: 'Ascensores centenarios, murales callejeros y atardeceres desde los cerros más coloridos de Chile.',
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=80',
      color: '#4c1d95',
      emoji: '🎨',
      tags: ['Arte', 'Ciudad', 'Cultura'],
    },
  ],

  CO: [
    {
      id: 'cartagena',
      city: 'Cartagena',
      tipo: 'Colonial / Caribe',
      tagline: 'La ciudad amurallada te espera',
      description: 'Murallas históricas, playas caribeñas y una gastronomía que mezcla culturas del mundo entero.',
      image: 'https://images.unsplash.com/photo-1584006682522-dc17d6c0d9ac?w=1600&q=80',
      color: '#7c2d12',
      emoji: '🏰',
      tags: ['Caribe', 'Historia', 'Playa'],
    },
    {
      id: 'medellin',
      city: 'Medellín',
      tipo: 'Eterna primavera',
      tagline: 'La ciudad de la eterna primavera',
      description: 'Innovación, flores y gente cálida. Medellín es la ciudad que se reinventó y no para de crecer.',
      image: 'https://images.unsplash.com/photo-1609365635836-45f9de80c6d1?w=1600&q=80',
      color: '#065f46',
      emoji: '🌺',
      tags: ['Ciudad', 'Cultura', 'Gastronomía'],
    },
    {
      id: 'bogota',
      city: 'Bogotá',
      tipo: 'Capital cultural',
      tagline: 'La capital que nunca duerme',
      description: 'Museos de clase mundial, barrios únicos y una escena gastronómica que se come el mundo.',
      image: 'https://images.unsplash.com/photo-1601123840261-71d0c70ad625?w=1600&q=80',
      color: '#1e3a5f',
      emoji: '🏙️',
      tags: ['Capital', 'Museo', 'Gastronomía'],
    },
    {
      id: 'santa-marta',
      city: 'Santa Marta',
      tipo: 'Caribe',
      tagline: 'Sierra Nevada hasta el mar',
      description: 'Donde la sierra Nevada llega al Caribe. Tayrona, Ciudad Perdida y playas salvajes te esperan.',
      image: 'https://images.unsplash.com/photo-1558980664-10e7170b5df9?w=1600&q=80',
      color: '#0c4a6e',
      emoji: '🏖️',
      tags: ['Caribe', 'Naturaleza', 'Aventura'],
    },
  ],

  AR: [
    {
      id: 'buenos-aires',
      city: 'Buenos Aires',
      tipo: 'Metrópoli',
      tagline: 'El Paris del sur',
      description: 'Tango, asado, arquitectura europea y una vida nocturna que no tiene horario de cierre.',
      image: 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=1600&q=80',
      color: '#1e3a5f',
      emoji: '🥩',
      tags: ['Ciudad', 'Tango', 'Gastronomía'],
    },
    {
      id: 'bariloche',
      city: 'Bariloche',
      tipo: 'Montaña / Lago',
      tagline: 'La Patagonia más accesible',
      description: 'Nieve en invierno, trekking en verano y el chocolate más famoso de Argentina.',
      image: 'https://images.unsplash.com/photo-1568543973870-45f5e4c6b706?w=1600&q=80',
      color: '#0f3460',
      emoji: '⛷️',
      tags: ['Montaña', 'Lago', 'Aventura'],
    },
    {
      id: 'mendoza',
      city: 'Mendoza',
      tipo: 'Vinos',
      tagline: 'Entre viñedos y la cordillera',
      description: 'El mejor Malbec del mundo y la cordillera de los Andes como telón de fondo.',
      image: 'https://images.unsplash.com/photo-1538037660071-5cb9c1bd8fc1?w=1600&q=80',
      color: '#4c1d95',
      emoji: '🍷',
      tags: ['Vinos', 'Montaña', 'Gastronomía'],
    },
    {
      id: 'ushuaia',
      city: 'Ushuaia',
      tipo: 'Fin del mundo',
      tagline: 'El fin del mundo empieza aquí',
      description: 'La ciudad más austral del planeta. Pingüinos, glaciares y la belleza salvaje de la Patagonia.',
      image: 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=1600&q=80',
      color: '#134e4a',
      emoji: '🐧',
      tags: ['Patagonia', 'Naturaleza', 'Aventura'],
    },
  ],

  MX: [
    {
      id: 'cdmx',
      city: 'Ciudad de México',
      tipo: 'Metrópoli',
      tagline: 'La ciudad que lo tiene todo',
      description: 'Museos, mercados, street food de clase mundial y una energía que no se encuentra en ningún otro lugar.',
      image: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=1600&q=80',
      color: '#1e3a5f',
      emoji: '🏙️',
      tags: ['Ciudad', 'Cultura', 'Gastronomía'],
    },
    {
      id: 'oaxaca',
      city: 'Oaxaca',
      tipo: 'Cultura',
      tagline: 'El corazón de México',
      description: 'Mole negro, mezcal, artesanías y una cultura viva que se celebra en cada esquina.',
      image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1600&q=80',
      color: '#7c2d12',
      emoji: '🌮',
      tags: ['Cultura', 'Gastronomía', 'Arte'],
    },
    {
      id: 'tulum',
      city: 'Tulum',
      tipo: 'Playa / Ruinas',
      tagline: 'Ruinas mayas frente al Caribe',
      description: 'Cenotes, selva, playas blancas y ruinas mayas sobre el mar turquesa.',
      image: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=1600&q=80',
      color: '#065f46',
      emoji: '🌴',
      tags: ['Playa', 'Ruinas', 'Naturaleza'],
    },
    {
      id: 'san-miguel',
      city: 'San Miguel de Allende',
      tipo: 'Colonial',
      tagline: 'La ciudad más bella de México',
      description: 'Calles empedradas, arquitectura barroca y una comunidad de artistas que hechiza a quien la visita.',
      image: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=1600&q=80',
      color: '#78350f',
      emoji: '🎨',
      tags: ['Colonial', 'Arte', 'Arquitectura'],
    },
  ],
}

export function getCountryBanners(countryCode) {
  return COUNTRY_BANNERS[countryCode] || COUNTRY_BANNERS.CL
}

export function getRandomCountryBanner(countryCode) {
  const banners = getCountryBanners(countryCode)
  return banners[Math.floor(Math.random() * banners.length)]
}
