// ─── USERS ────────────────────────────────────────────────────────────────────
export const mockUsers = [
  {
    id: 'u1', name: 'Camila Torres', email: 'camila@rukka.cl', password: 'demo123',
    emailVerified: true,
    avatar: 'https://i.pravatar.cc/150?img=47',
    coverPhoto: 'https://picsum.photos/seed/camila-cover/900/300',
    location: 'Santiago, Chile', city: 'Santiago', country: 'Chile',
    bio: 'Arquitecta de Santiago apasionada por el diseño y los viajes. Mi departamento en Providencia es mi hogar favorito, pero me encanta explorar el mundo.',
    languages: ['Español', 'English', 'Français'], verified: true,
    joinDate: '2024-01-10', rating: 4.9, reviewCount: 18, exchanges: 14,
  },
  {
    id: 'u2', name: 'Felipe Muñoz', email: 'felipe@rukka.cl', password: 'demo123',
    emailVerified: true,
    avatar: 'https://i.pravatar.cc/150?img=60',
    coverPhoto: 'https://picsum.photos/seed/felipe-cover/900/300',
    location: 'Valparaíso, Chile', city: 'Valparaíso', country: 'Chile',
    bio: 'Fotógrafo y viajero. Tengo una casona colorida en los cerros de Valparaíso con vistas al Pacífico. Me encantan los intercambios culturales.',
    languages: ['Español', 'English'], verified: true,
    joinDate: '2024-02-20', rating: 4.8, reviewCount: 12, exchanges: 9,
  },
  {
    id: 'u3', name: 'Sofía Riquelme', email: 'sofia@rukka.cl', password: 'demo123',
    emailVerified: true,
    avatar: 'https://i.pravatar.cc/150?img=44',
    coverPhoto: 'https://picsum.photos/seed/sofia-cover/900/300',
    location: 'Pucón, Chile', city: 'Pucón', country: 'Chile',
    bio: 'Guía de montaña en la región de los Lagos. Vivo al pie del volcán Villarrica en una cabaña rodeada de naturaleza. Perfecta para amantes del outdoor.',
    languages: ['Español', 'Deutsch', 'English'], verified: true,
    joinDate: '2024-03-05', rating: 5.0, reviewCount: 21, exchanges: 17,
  },
  {
    id: 'u4', name: 'Martín Vega', email: 'martin@rukka.cl', password: 'demo123',
    emailVerified: true,
    avatar: 'https://i.pravatar.cc/150?img=32',
    coverPhoto: 'https://picsum.photos/seed/martin-cover/900/300',
    location: 'San Pedro de Atacama, Chile', city: 'San Pedro de Atacama', country: 'Chile',
    bio: 'Astrofísico y amante del desierto. Mi casa de adobe en Atacama tiene una terraza perfecta para observar el cielo más despejado del mundo.',
    languages: ['Español', 'English', 'Italiano'], verified: true,
    joinDate: '2024-01-28', rating: 4.9, reviewCount: 15, exchanges: 11,
  },
  {
    id: 'u5', name: 'Ana González', email: 'ana@rukka.cl', password: 'demo123',
    emailVerified: true,
    avatar: 'https://i.pravatar.cc/150?img=33',
    coverPhoto: 'https://picsum.photos/seed/ana-cover/900/300',
    location: 'Viña del Mar, Chile', city: 'Viña del Mar', country: 'Chile',
    bio: 'Diseñadora gráfica en Viña del Mar. Mi apartamento en Reñaca tiene vistas directas al Pacífico y está a 5 min de la playa.',
    languages: ['Español', 'English', 'Português'], verified: false,
    joinDate: '2024-04-12', rating: 4.6, reviewCount: 7, exchanges: 5,
  },
  {
    id: 'u6', name: 'Lars Andersen', email: 'lars@rukka.cl', password: 'demo123',
    emailVerified: true,
    avatar: 'https://i.pravatar.cc/150?img=11',
    coverPhoto: 'https://picsum.photos/seed/lars-cover/900/300',
    location: 'Barcelona, España', city: 'Barcelona', country: 'España',
    bio: 'Arquitecto danés viviendo en Barcelona. Mi apartamento en el Eixample es moderno, luminoso y está en el corazón de la ciudad.',
    languages: ['English', 'Español', 'Dansk', 'Deutsch'], verified: true,
    joinDate: '2023-11-15', rating: 4.8, reviewCount: 31, exchanges: 24,
  },
  {
    id: 'u7', name: 'Yuki Nakamura', email: 'yuki@rukka.cl', password: 'demo123',
    emailVerified: true,
    avatar: 'https://i.pravatar.cc/150?img=45',
    coverPhoto: 'https://picsum.photos/seed/yuki-cover/900/300',
    location: 'Tokio, Japón', city: 'Tokio', country: 'Japón',
    bio: 'Diseñadora en Shibuya. Mi estudio mezcla el minimalismo japonés con toques contemporáneos. La experiencia más auténtica de Tokio.',
    languages: ['日本語', 'English', 'Español'], verified: true,
    joinDate: '2024-02-01', rating: 5.0, reviewCount: 14, exchanges: 10,
  },
  {
    id: 'u8', name: 'Luisa Ferrari', email: 'luisa@rukka.cl', password: 'demo123',
    emailVerified: true,
    avatar: 'https://i.pravatar.cc/150?img=49',
    coverPhoto: 'https://picsum.photos/seed/luisa-cover/900/300',
    location: 'Roma, Italia', city: 'Roma', country: 'Italia',
    bio: 'Sommelier y amante de la historia romana. Mi apartamento en el Trastevere tiene frescos originales del siglo XIX. La Roma más auténtica.',
    languages: ['Italiano', 'English', 'Español', 'Français'], verified: true,
    joinDate: '2023-12-10', rating: 4.9, reviewCount: 22, exchanges: 18,
  },
  {
    id: 'u9', name: 'Emma Wilson', email: 'emma@rukka.cl', password: 'demo123',
    emailVerified: true,
    avatar: 'https://i.pravatar.cc/150?img=23',
    coverPhoto: 'https://picsum.photos/seed/emma-cover/900/300',
    location: 'Lisboa, Portugal', city: 'Lisboa', country: 'Portugal',
    bio: 'Escritora y nómada digital viviendo en Alfama. Mi casa con azulejos originales y vistas al Tejo es uno de mis lugares favoritos del mundo.',
    languages: ['English', 'Português', 'Español'], verified: true,
    joinDate: '2024-01-05', rating: 4.7, reviewCount: 19, exchanges: 14,
  },
  {
    id: 'u10', name: 'Pablo Díaz', email: 'pablo@rukka.cl', password: 'demo123',
    emailVerified: true,
    avatar: 'https://i.pravatar.cc/150?img=15',
    coverPhoto: 'https://picsum.photos/seed/pablo-cover/900/300',
    location: 'Buenos Aires, Argentina', city: 'Buenos Aires', country: 'Argentina',
    bio: 'Músico y tanguero porteño. Mi departamento en Palermo Soho es el punto de partida perfecto para vivir el Buenos Aires cultural.',
    languages: ['Español', 'English', 'Italiano'], verified: true,
    joinDate: '2024-03-18', rating: 4.7, reviewCount: 9, exchanges: 7,
  },
]

// ─── HOMES ────────────────────────────────────────────────────────────────────
export const mockHomes = [
  {
    id: 'h1', userId: 'u1',
    title: 'Depto moderno en Providencia con terraza',
    description: 'Luminoso departamento de 90m² en el barrio más residencial de Santiago. Planta abierta con cocina integrada, dos habitaciones, un baño completo y una terraza privada con parrilla. A pasos del metro Baquedano y del Parque Bicentenario. La decoración combina el diseño contemporáneo con arte chileno local. Internet de fibra óptica, netflix y todas las comodidades del hogar.',
    shortDescription: 'Luminoso y moderno, con terraza y parrilla en el mejor barrio de Santiago.',
    type: 'Departamento', location: 'Providencia, Santiago', city: 'Santiago', country: 'Chile',
    bedrooms: 2, bathrooms: 1, maxGuests: 4, size: 90, floor: 5,
    amenities: ['WiFi fibra óptica', 'Cocina equipada', 'Lavadora', 'AC', 'Calefacción', 'Smart TV', 'Terraza con parrilla', 'Ascensor', 'Estacionamiento'],
    images: ['https://picsum.photos/seed/santiago1/800/500', 'https://picsum.photos/seed/santiago2/800/500', 'https://picsum.photos/seed/santiago3/800/500', 'https://picsum.photos/seed/santiago4/800/500'],
    availabilityPeriods: [
      { id: 'av1', start: '2025-03-01', end: '2025-03-31' },
      { id: 'av2', start: '2025-06-15', end: '2025-07-15' },
      { id: 'av3', start: '2025-09-01', end: '2025-09-30' },
    ],
    rating: 4.9, reviewCount: 18,
    nearbyAttractions: ['Metro Baquedano (3 min)', 'Parque Bicentenario (8 min)', 'Barrio Italia (10 min)'],
    reviews: [
      { id: 'r1', userId: 'u6', userName: 'Lars Andersen', userAvatar: 'https://i.pravatar.cc/150?img=11', rating: 5, comment: 'Departamento increíble. Santiago es una ciudad fascinante y Camila es una anfitriona perfecta. ¡Volvería mil veces!', date: '2024-11-20' },
      { id: 'r2', userId: 'u7', userName: 'Yuki Nakamura', userAvatar: 'https://i.pravatar.cc/150?img=45', rating: 5, comment: 'Perfect apartment in a great location. Santiago surprised me — incredible food and culture!', date: '2024-10-15' },
    ],
    featured: true,
  },
  {
    id: 'h2', userId: 'u2',
    title: 'Casona colorida en los cerros de Valparaíso',
    description: 'Una casona única en los icónicos cerros de Valparaíso, pintada con los colores vibrantes del barrio. Tres habitaciones, un gran salón con vista al puerto y al Pacífico, cocina rústica equipada y una terraza-mirador espectacular. Llegada al cerro en el histórico ascensor Concepción, a pasos de las mejores galerías de arte callejero y restaurantes bohemios del puerto.',
    shortDescription: 'Casa icónica en los cerros de Valparaíso con vistas al Pacífico y el puerto.',
    type: 'Casa', location: 'Cerro Alegre, Valparaíso', city: 'Valparaíso', country: 'Chile',
    bedrooms: 3, bathrooms: 2, maxGuests: 6, size: 130, floor: null,
    amenities: ['WiFi', 'Cocina equipada', 'Lavadora', 'Calefacción', 'Smart TV', 'Terraza-mirador', 'Jardín', 'Parrilla'],
    images: ['https://picsum.photos/seed/valpo1/800/500', 'https://picsum.photos/seed/valpo2/800/500', 'https://picsum.photos/seed/valpo3/800/500', 'https://picsum.photos/seed/valpo4/800/500'],
    availabilityPeriods: [
      { id: 'av4', start: '2025-02-15', end: '2025-03-15' },
      { id: 'av5', start: '2025-07-01', end: '2025-08-31' },
    ],
    rating: 4.8, reviewCount: 12,
    nearbyAttractions: ['Ascensor Concepción (2 min)', 'Plaza Aníbal Pinto (5 min)', 'Playas de Viña (20 min)'],
    reviews: [
      { id: 'r3', userId: 'u8', userName: 'Luisa Ferrari', userAvatar: 'https://i.pravatar.cc/150?img=49', rating: 5, comment: 'Valparaíso me robó el corazón. La casona de Felipe es mágica, llena de arte y con vistas increíbles. ¡Perfecta!', date: '2024-12-01' },
    ],
    featured: true,
  },
  {
    id: 'h3', userId: 'u3',
    title: 'Cabaña de montaña al pie del Volcán Villarrica',
    description: 'Cabaña de madera nativa con vista directa al imponente Volcán Villarrica en Pucón. Dos habitaciones acogedoras, chimenea a leña, jacuzzi exterior con vistas al volcán y jardín con acceso directo al río. Ideal para senderismo, kayak, rafting y esquí en temporada de invierno. A 10 minutos del centro de Pucón y del lago Villarrica. Una experiencia única en contacto con la naturaleza patagónica.',
    shortDescription: 'Cabaña nativa con jacuzzi y vista al Volcán Villarrica. Naturaleza pura en Pucón.',
    type: 'Cabaña', location: 'Pucón, Araucanía', city: 'Pucón', country: 'Chile',
    bedrooms: 2, bathrooms: 1, maxGuests: 4, size: 80, floor: null,
    amenities: ['WiFi', 'Cocina equipada', 'Lavadora', 'Chimenea a leña', 'Jacuzzi exterior', 'Parrilla', 'Jardín', 'Acceso al río', 'Bicicletas'],
    images: ['https://picsum.photos/seed/pucon1/800/500', 'https://picsum.photos/seed/pucon2/800/500', 'https://picsum.photos/seed/pucon3/800/500', 'https://picsum.photos/seed/pucon4/800/500'],
    availabilityPeriods: [
      { id: 'av6', start: '2025-01-15', end: '2025-02-28' },
      { id: 'av7', start: '2025-07-01', end: '2025-08-15' },
      { id: 'av8', start: '2025-11-01', end: '2025-12-15' },
    ],
    rating: 5.0, reviewCount: 21,
    nearbyAttractions: ['Volcán Villarrica (15 min)', 'Lago Villarrica (10 min)', 'Centro de Pucón (10 min)', 'Termas de Huife (25 min)'],
    reviews: [
      { id: 'r4', userId: 'u1', userName: 'Camila Torres', userAvatar: 'https://i.pravatar.cc/150?img=47', rating: 5, comment: 'La cabaña de Sofía es absolutamente mágica. El jacuzzi con vista al volcán al atardecer... un momento para nunca olvidar.', date: '2024-11-28' },
    ],
    featured: true,
  },
  {
    id: 'h4', userId: 'u4',
    title: 'Casa de adobe en el corazón del Desierto de Atacama',
    description: 'Una experiencia única en una casa de adobe construida con técnica local, en el pueblo de San Pedro de Atacama. Dos habitaciones con arquitectura tradicional atacameña, patio interior con jardín de cactus y una terraza astronómica ideal para observar el cielo nocturno más limpio del mundo. A pasos de los mejores restaurantes locales, la iglesia colonial y los tours al Valle de la Luna.',
    shortDescription: 'Casa de adobe tradicional con terraza astronómica en San Pedro de Atacama.',
    type: 'Casa', location: 'San Pedro de Atacama, Antofagasta', city: 'San Pedro de Atacama', country: 'Chile',
    bedrooms: 2, bathrooms: 1, maxGuests: 4, size: 70, floor: null,
    amenities: ['WiFi', 'Cocina equipada', 'Calefacción', 'Smart TV', 'Patio interior', 'Telescopio', 'Terraza astronómica', 'Bicicletas'],
    images: ['https://picsum.photos/seed/atacama1/800/500', 'https://picsum.photos/seed/atacama2/800/500', 'https://picsum.photos/seed/atacama3/800/500', 'https://picsum.photos/seed/atacama4/800/500'],
    availabilityPeriods: [
      { id: 'av9', start: '2025-04-01', end: '2025-05-31' },
      { id: 'av10', start: '2025-08-01', end: '2025-09-30' },
    ],
    rating: 4.9, reviewCount: 15,
    nearbyAttractions: ['Valle de la Luna (15 min)', 'Géiseres del Tatio (60 min)', 'Lagunas Altiplánicas (90 min)'],
    reviews: [
      { id: 'r5', userId: 'u9', userName: 'Emma Wilson', userAvatar: 'https://i.pravatar.cc/150?img=23', rating: 5, comment: 'The Atacama is out of this world! Martín\'s adobe house was the perfect base. Stargazing from the rooftop was unforgettable.', date: '2024-09-20' },
    ],
    featured: true,
  },
  {
    id: 'h5', userId: 'u5',
    title: 'Depto con vistas al Pacífico en Reñaca, Viña del Mar',
    description: 'Moderno departamento en el exclusivo sector de Reñaca con vista directa al Océano Pacífico desde el living y la terraza. Una habitación doble, baño completo, cocina equipada y terraza con asientos exteriores para disfrutar el atardecer sobre el océano. A 5 minutos caminando de la playa y el Casino de Viña. El destino de playa más famoso de Chile a tu disposición.',
    shortDescription: 'Depto con vista al Pacífico y terraza frente al mar en Reñaca, Viña del Mar.',
    type: 'Departamento', location: 'Reñaca, Viña del Mar', city: 'Viña del Mar', country: 'Chile',
    bedrooms: 1, bathrooms: 1, maxGuests: 2, size: 55, floor: 8,
    amenities: ['WiFi', 'Cocina equipada', 'AC', 'Smart TV', 'Terraza con vista al mar', 'Ascensor', 'Estacionamiento'],
    images: ['https://picsum.photos/seed/vina1/800/500', 'https://picsum.photos/seed/vina2/800/500', 'https://picsum.photos/seed/vina3/800/500', 'https://picsum.photos/seed/vina4/800/500'],
    availabilityPeriods: [
      { id: 'av11', start: '2025-01-01', end: '2025-02-28' },
      { id: 'av12', start: '2025-12-01', end: '2025-12-31' },
    ],
    rating: 4.6, reviewCount: 7,
    nearbyAttractions: ['Playa Reñaca (5 min)', 'Casino Viña (20 min)', 'Jardín Botánico (30 min)'],
    reviews: [],
    featured: false,
  },
  {
    id: 'h6', userId: 'u6',
    title: 'Apartamento diseñador en el Eixample, Barcelona',
    description: 'Espectacular apartamento de diseño en el corazón del Eixample barcelonés, a pasos de la Sagrada Família y del Passeig de Gràcia. 85m² completamente reformados con materiales de alta calidad: suelos de parquet, cocina de diseño, baño con ducha lluvia. Techos de 3m con molduras originales modernistas. Dos habitaciones, salón amplio con sofá cama y terraza con vistas a la ciudad.',
    shortDescription: 'Apartamento modernista reformado con terraza en el corazón del Eixample.',
    type: 'Departamento', location: 'Eixample, Barcelona', city: 'Barcelona', country: 'España',
    bedrooms: 2, bathrooms: 1, maxGuests: 4, size: 85, floor: 3,
    amenities: ['WiFi fibra', 'Cocina de diseño', 'Lavadora', 'AC', 'Smart TV', 'Terraza', 'Ascensor', 'Balcón'],
    images: ['https://picsum.photos/seed/barcelona1/800/500', 'https://picsum.photos/seed/barcelona2/800/500', 'https://picsum.photos/seed/barcelona3/800/500', 'https://picsum.photos/seed/barcelona4/800/500'],
    availabilityPeriods: [
      { id: 'av13', start: '2025-03-01', end: '2025-03-31' },
      { id: 'av14', start: '2025-05-01', end: '2025-06-30' },
      { id: 'av15', start: '2025-09-01', end: '2025-10-31' },
    ],
    rating: 4.8, reviewCount: 31,
    nearbyAttractions: ['Sagrada Família (8 min)', 'Casa Batlló (10 min)', 'Passeig de Gràcia (5 min)'],
    reviews: [
      { id: 'r6', userId: 'u1', userName: 'Camila Torres', userAvatar: 'https://i.pravatar.cc/150?img=47', rating: 5, comment: '¡Barcelona es simplemente increíble! El apartamento de Lars es perfecto: bien ubicado, limpio, moderno. ¡Volveré!', date: '2024-10-10' },
    ],
    featured: true,
  },
  {
    id: 'h7', userId: 'u7',
    title: 'Estudio minimalista en Shibuya, Tokio',
    description: 'Estudio diseñado bajo la filosofía del wabi-sabi japonés, en pleno corazón de Shibuya. 38m² perfectamente optimizados: zona de dormir con futon tradicional japonés, baño con ofuro (bañera japonesa profunda), cocineta equipada y escritorio zen para trabajar. A 3 minutos del cruce de Shibuya y con acceso directo al metro hacia todos los barrios de Tokio.',
    shortDescription: 'Experiencia auténtica japonesa a metros del famoso cruce de Shibuya.',
    type: 'Estudio', location: 'Shibuya, Tokio', city: 'Tokio', country: 'Japón',
    bedrooms: 1, bathrooms: 1, maxGuests: 2, size: 38, floor: 9,
    amenities: ['WiFi ultra-rápido', 'Cocineta', 'Lavadora', 'AC reversible', 'Smart TV', 'Ofuro japonés', 'Vista ciudad'],
    images: ['https://picsum.photos/seed/tokyo1/800/500', 'https://picsum.photos/seed/tokyo2/800/500', 'https://picsum.photos/seed/tokyo3/800/500', 'https://picsum.photos/seed/tokyo4/800/500'],
    availabilityPeriods: [
      { id: 'av16', start: '2025-04-01', end: '2025-04-30' },
      { id: 'av17', start: '2025-10-01', end: '2025-10-31' },
    ],
    rating: 5.0, reviewCount: 14,
    nearbyAttractions: ['Cruce Shibuya (3 min)', 'Harajuku (15 min)', 'Shinjuku (20 min)'],
    reviews: [],
    featured: false,
  },
  {
    id: 'h8', userId: 'u8',
    title: 'Apartamento con frescos en Trastevere, Roma',
    description: 'Encantador apartamento en el corazón del Trastevere, el barrio más romántico de Roma. Segundo piso de un palazzo del 1800, con techos abovedados y frescos originales restaurados. Dos habitaciones, salón con vista a la piazza interior y pequeña terraza con macetas de laurel y lavanda. A pasos de los mejores restaurantes de pasta fresca y la animada vida nocturna del barrio.',
    shortDescription: 'Palazzo del 1800 con frescos originales en el barrio más romántico de Roma.',
    type: 'Departamento', location: 'Trastevere, Roma', city: 'Roma', country: 'Italia',
    bedrooms: 2, bathrooms: 1, maxGuests: 4, size: 75, floor: 2,
    amenities: ['WiFi', 'Cocina equipada', 'Lavadora', 'AC', 'Smart TV', 'Terraza', 'Bodega de vinos'],
    images: ['https://picsum.photos/seed/rome1/800/500', 'https://picsum.photos/seed/rome2/800/500', 'https://picsum.photos/seed/rome3/800/500', 'https://picsum.photos/seed/rome4/800/500'],
    availabilityPeriods: [
      { id: 'av18', start: '2025-03-15', end: '2025-04-15' },
      { id: 'av19', start: '2025-06-01', end: '2025-07-31' },
      { id: 'av20', start: '2025-10-01', end: '2025-11-30' },
    ],
    rating: 4.9, reviewCount: 22,
    nearbyAttractions: ['Vaticano (15 min)', 'Piazza Navona (10 min)', 'Coliseo (25 min)'],
    reviews: [
      { id: 'r7', userId: 'u3', userName: 'Sofía Riquelme', userAvatar: 'https://i.pravatar.cc/150?img=44', rating: 5, comment: 'Roma me dejó sin palabras. Y el apartamento de Luisa con esos frescos originales es un museo habitado. Grazie!', date: '2024-11-05' },
    ],
    featured: true,
  },
  {
    id: 'h9', userId: 'u9',
    title: 'Casa con azulejos en Alfama, Lisboa',
    description: 'Casa tradicional portuguesa en el barrio histórico de Alfama, con azulejos originales del siglo XVIII en la fachada y el interior. Tres pisos conectados por una escalera de madera crujiente y llena de encanto. Dos habitaciones, cocina tradicional azulejada, salón con lareira y mirador con vista sobre el Castillo de São Jorge y el Tejo. Fado en vivo a pasos de tu puerta.',
    shortDescription: 'Casa con azulejos originales del siglo XVIII y vistas al Tejo en el histórico Alfama.',
    type: 'Casa', location: 'Alfama, Lisboa', city: 'Lisboa', country: 'Portugal',
    bedrooms: 2, bathrooms: 2, maxGuests: 4, size: 95, floor: null,
    amenities: ['WiFi', 'Cocina equipada', 'Lavadora', 'Calefacción', 'Smart TV', 'Terraza-mirador', 'Lareira'],
    images: ['https://picsum.photos/seed/lisbon1/800/500', 'https://picsum.photos/seed/lisbon2/800/500', 'https://picsum.photos/seed/lisbon3/800/500', 'https://picsum.photos/seed/lisbon4/800/500'],
    availabilityPeriods: [
      { id: 'av21', start: '2025-02-01', end: '2025-03-31' },
      { id: 'av22', start: '2025-05-15', end: '2025-06-30' },
      { id: 'av23', start: '2025-09-01', end: '2025-10-31' },
    ],
    rating: 4.7, reviewCount: 19,
    nearbyAttractions: ['Castillo São Jorge (5 min)', 'Sé de Lisboa (8 min)', 'Panteón Nacional (10 min)'],
    reviews: [],
    featured: true,
  },
  {
    id: 'h10', userId: 'u10',
    title: 'Loft en Palermo Soho, Buenos Aires',
    description: 'Increíble loft de ladrillo visto en el barrio más cool de Buenos Aires. 110m² abiertos con doble altura, grandes ventanales industriales, cocina equipada de diseño y terraza privada con parrilla. En pleno Palermo Soho, rodeado de los mejores bares, restaurantes, teatros independientes y boutiques de moda argentina. A pasos de la movida nocturna más interesante de LATAM.',
    shortDescription: 'Loft industrial con terraza y parrilla en el epicentro cultural de Palermo Soho.',
    type: 'Loft', location: 'Palermo Soho, Buenos Aires', city: 'Buenos Aires', country: 'Argentina',
    bedrooms: 2, bathrooms: 1, maxGuests: 4, size: 110, floor: 1,
    amenities: ['WiFi', 'Cocina de diseño', 'Lavadora', 'AC', 'Smart TV', 'Terraza con parrilla', 'Estacionamiento'],
    images: ['https://picsum.photos/seed/bsas1/800/500', 'https://picsum.photos/seed/bsas2/800/500', 'https://picsum.photos/seed/bsas3/800/500', 'https://picsum.photos/seed/bsas4/800/500'],
    availabilityPeriods: [
      { id: 'av24', start: '2025-03-01', end: '2025-04-30' },
      { id: 'av25', start: '2025-08-01', end: '2025-09-30' },
    ],
    rating: 4.7, reviewCount: 9,
    nearbyAttractions: ['Teatro Colón (20 min)', 'MALBA (15 min)', 'Av. Corrientes (25 min)'],
    reviews: [],
    featured: false,
  },
]

// ─── TRAVEL WISHES ────────────────────────────────────────────────────────────
export const mockTravelWishes = [
  {
    id: 'tw1', userId: 'u1', fromCity: 'Santiago', fromCountry: 'Chile',
    toCity: 'Barcelona', toCountry: 'España',
    startDate: '2025-03-10', endDate: '2025-03-25',
    neededCapacity: 2, message: 'Quiero conocer Barcelona en primavera. Ofrezco mi depto en Providencia para las mismas fechas.',
    createdAt: '2024-12-01',
  },
  {
    id: 'tw2', userId: 'u6', fromCity: 'Barcelona', fromCountry: 'España',
    toCity: 'Santiago', toCountry: 'Chile',
    startDate: '2025-03-10', endDate: '2025-03-25',
    neededCapacity: 2, message: 'Always wanted to explore Santiago and Patagonia! I offer my Eixample apartment.',
    createdAt: '2024-12-05',
  },
  {
    id: 'tw3', userId: 'u3', fromCity: 'Pucón', fromCountry: 'Chile',
    toCity: 'Roma', toCountry: 'Italia',
    startDate: '2025-10-15', endDate: '2025-10-30',
    neededCapacity: 2, message: 'Siempre soñé con ver el Coliseo. Ofrezco mi cabaña en Pucón en primavera chilena.',
    createdAt: '2024-12-10',
  },
  {
    id: 'tw4', userId: 'u8', fromCity: 'Roma', fromCountry: 'Italia',
    toCity: 'Pucón', toCountry: 'Chile',
    startDate: '2025-10-15', endDate: '2025-10-31',
    neededCapacity: 2, message: 'Ho sempre sognato la Patagonia! Offro il mio appartamento a Trastevere.',
    createdAt: '2024-12-12',
  },
  {
    id: 'tw5', userId: 'u2', fromCity: 'Valparaíso', fromCountry: 'Chile',
    toCity: 'Lisboa', toCountry: 'Portugal',
    startDate: '2025-05-20', endDate: '2025-06-10',
    neededCapacity: 2, message: 'Valparaíso y Lisboa tienen muchas similitudes: puertos, cerros, ascensores. ¡Quiero conocer Lisboa!',
    createdAt: '2024-12-15',
  },
]

// ─── EXCHANGE REQUESTS ─────────────────────────────────────────────────────────
export const mockExchangeRequests = [
  {
    id: 'er1',
    fromUserId: 'u1', toUserId: 'u6',
    fromHomeId: 'h1', toHomeId: 'h6',
    startDate: '2025-03-10', endDate: '2025-03-25',
    status: 'accepted',
    message: 'Hi Lars! We found a perfect match. I want to visit Barcelona March 10-25 and you want to visit Santiago the same dates. Shall we swap?',
    createdAt: '2024-12-06', isBilateral: true,
  },
]

export const AMENITY_ICONS = {
  'WiFi': '📶', 'WiFi fibra óptica': '📶', 'WiFi fibra': '📶', 'WiFi ultra-rápido': '📶',
  'Cocina equipada': '🍳', 'Cocina de diseño': '🍳', 'Cocineta': '🍳',
  'Lavadora': '🫧', 'AC': '❄️', 'AC reversible': '❄️', 'Calefacción': '🔥',
  'Smart TV': '📺', 'Terraza': '🏙️', 'Terraza con parrilla': '🥩',
  'Terraza-mirador': '🔭', 'Terraza con vista al mar': '🌊',
  'Ascensor': '🛗', 'Estacionamiento': '🚗', 'Chimenea a leña': '🪵',
  'Jacuzzi exterior': '♨️', 'Parrilla': '🔥', 'Bicicletas': '🚴',
  'Telescopio': '🔭', 'Terraza astronómica': '🌌', 'Ofuro japonés': '🛁',
  'Jardín': '🌿', 'Acceso al río': '🏞️', 'Lareira': '🔥', 'Bodega de vinos': '🍷',
}
