export const COUNTRIES = [
  {
    code: 'CL', name: 'Chile', currency: 'CLP', locale: 'es-CL',
    flag: '🇨🇱', mpLocale: 'es-CL',
    regions: [
      { code: 'RM',   name: 'Región Metropolitana',
        cities: ['Santiago', 'Maipú', 'Las Condes', 'Providencia', 'Ñuñoa', 'La Florida', 'Vitacura', 'Pudahuel', 'San Bernardo', 'Peñalolén'] },
      { code: 'V',    name: 'Valparaíso',
        cities: ['Valparaíso', 'Viña del Mar', 'Quilpué', 'Villa Alemana', 'Concón', 'San Antonio'] },
      { code: 'VIII', name: 'Biobío',
        cities: ['Concepción', 'Talcahuano', 'Chillán', 'Los Ángeles', 'Hualpén'] },
      { code: 'IX',   name: 'La Araucanía',
        cities: ['Temuco', 'Padre Las Casas', 'Villarrica', 'Pucón', 'Angol'] },
      { code: 'X',    name: 'Los Lagos',
        cities: ['Puerto Montt', 'Osorno', 'Castro', 'Puerto Varas', 'Ancud'] },
      { code: 'II',   name: 'Antofagasta',
        cities: ['Antofagasta', 'Calama', 'Tocopilla', 'San Pedro de Atacama'] },
      { code: 'IV',   name: 'Coquimbo',
        cities: ['La Serena', 'Coquimbo', 'Ovalle', 'Illapel'] },
      { code: 'VII',  name: 'Maule',
        cities: ['Talca', 'Curicó', 'Linares', 'Constitución'] },
      { code: 'XIV',  name: 'Los Ríos',
        cities: ['Valdivia', 'La Unión', 'Panguipulli', 'Río Bueno'] },
      { code: 'XI',   name: 'Aysén',
        cities: ['Coyhaique', 'Puerto Aysén', 'Chile Chico'] },
      { code: 'XII',  name: 'Magallanes',
        cities: ['Punta Arenas', 'Puerto Natales', 'Porvenir'] },
    ],
  },
  {
    code: 'MX', name: 'México', currency: 'MXN', locale: 'es-MX',
    flag: '🇲🇽', mpLocale: 'es-MX',
    regions: [
      { code: 'CDMX', name: 'Ciudad de México',
        cities: ['Ciudad de México', 'Coyoacán', 'Polanco', 'Roma Norte', 'Condesa', 'Xochimilco'] },
      { code: 'JAL',  name: 'Jalisco',
        cities: ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Puerto Vallarta', 'Lagos de Moreno'] },
      { code: 'NL',   name: 'Nuevo León',
        cities: ['Monterrey', 'San Pedro Garza García', 'Santa Catarina', 'Apodaca'] },
      { code: 'YUC',  name: 'Yucatán',
        cities: ['Mérida', 'Valladolid', 'Tizimín', 'Progreso'] },
      { code: 'OAX',  name: 'Oaxaca',
        cities: ['Oaxaca de Juárez', 'Puerto Escondido', 'Huatulco', 'Juchitán'] },
      { code: 'QROO', name: 'Quintana Roo',
        cities: ['Cancún', 'Playa del Carmen', 'Tulum', 'Cozumel', 'Isla Mujeres'] },
      { code: 'BCN',  name: 'Baja California',
        cities: ['Tijuana', 'Ensenada', 'Mexicali', 'Rosarito'] },
      { code: 'GTO',  name: 'Guanajuato',
        cities: ['León', 'Guanajuato', 'San Miguel de Allende', 'Irapuato'] },
      { code: 'PUE',  name: 'Puebla',
        cities: ['Puebla', 'Atlixco', 'Tehuacán', 'Cholula'] },
      { code: 'SIN',  name: 'Sinaloa',
        cities: ['Mazatlán', 'Culiacán', 'Los Mochis', 'Guasave'] },
    ],
  },
  {
    code: 'CO', name: 'Colombia', currency: 'COP', locale: 'es-CO',
    flag: '🇨🇴', mpLocale: 'es-CO',
    regions: [
      { code: 'DC',  name: 'Bogotá D.C.',
        cities: ['Bogotá', 'Usaquén', 'Chapinero', 'Suba', 'Kennedy'] },
      { code: 'ANT', name: 'Antioquia',
        cities: ['Medellín', 'El Poblado', 'Bello', 'Itagüí', 'Envigado', 'Laureles'] },
      { code: 'VAC', name: 'Valle del Cauca',
        cities: ['Cali', 'Buenaventura', 'Palmira'] },
      { code: 'ATL', name: 'Atlántico',
        cities: ['Barranquilla', 'Soledad', 'Malambo'] },
      { code: 'BOL', name: 'Bolívar',
        cities: ['Cartagena de Indias', 'Magangué', 'El Carmen de Bolívar'] },
      { code: 'SAN', name: 'Santander',
        cities: ['Bucaramanga', 'Floridablanca', 'Girón', 'Piedecuesta'] },
      { code: 'CUN', name: 'Cundinamarca',
        cities: ['Zipaquirá', 'Soacha', 'Fusagasugá', 'Facatativá'] },
      { code: 'NAR', name: 'Nariño',
        cities: ['Pasto', 'Ipiales', 'Tumaco'] },
      { code: 'RIS', name: 'Risaralda',
        cities: ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal'] },
      { code: 'CAL', name: 'Caldas',
        cities: ['Manizales', 'La Dorada', 'Chinchiná'] },
    ],
  },
  {
    code: 'AR', name: 'Argentina', currency: 'ARS', locale: 'es-AR',
    flag: '🇦🇷', mpLocale: 'es-AR',
    regions: [
      { code: 'CABA', name: 'Buenos Aires (CABA)',
        cities: ['Buenos Aires', 'Palermo', 'Recoleta', 'San Telmo', 'Belgrano', 'Villa Crespo'] },
      { code: 'BA',   name: 'Provincia de Buenos Aires',
        cities: ['La Plata', 'Mar del Plata', 'Bahía Blanca', 'Quilmes', 'Tigre', 'Pilar'] },
      { code: 'CBA',  name: 'Córdoba',
        cities: ['Córdoba', 'Alta Gracia', 'Villa Carlos Paz', 'Río Cuarto'] },
      { code: 'SFE',  name: 'Santa Fe',
        cities: ['Rosario', 'Santa Fe', 'Rafaela', 'Venado Tuerto'] },
      { code: 'MZA',  name: 'Mendoza',
        cities: ['Mendoza', 'San Rafael', 'Luján de Cuyo', 'Maipú'] },
      { code: 'PAT',  name: 'Patagonia',
        cities: ['Bariloche', 'El Bolsón', 'San Martín de los Andes', 'Puerto Madryn'] },
      { code: 'SAL',  name: 'Salta',
        cities: ['Salta', 'Cafayate', 'San Lorenzo', 'Orán'] },
      { code: 'JUJ',  name: 'Jujuy',
        cities: ['San Salvador de Jujuy', 'Palpalá', 'Purmamarca'] },
      { code: 'TUC',  name: 'Tucumán',
        cities: ['San Miguel de Tucumán', 'Tafí Viejo', 'Yerba Buena'] },
      { code: 'NEU',  name: 'Neuquén',
        cities: ['Neuquén', 'Zapala', 'San Martín de los Andes', 'Cutral-Có'] },
    ],
  },
]

export const getCountry    = (code)                     => COUNTRIES.find(c => c.code === code)
export const getRegions    = (countryCode)              => getCountry(countryCode)?.regions || []
export const getCities     = (countryCode, regionCode)  => getRegions(countryCode).find(r => r.code === regionCode)?.cities || []
export const getAllCities  = (countryCode)              => getRegions(countryCode).flatMap(r => r.cities)
